import { NigerianTaxCalculator } from '../modules/payroll/calculator/nigerian-tax-calculator.js';

export function defaultMemoryStoreData() {
  const demoTenantId = 'tenant_greenfield_100';
  const demoCampusId = 'campus_main_01';
  const demoAcademicYearId = 'ay_2026_2027';
  const demoTermId = 'term_first_2026';
  const demoClassId = 'cls_grade10_a';
  const demoSubjectId = 'sub_math_101';
  const demoOwnerId = 'user_owner_001';
  const demoStudentId = 'std_john_doe_01';
  const demoFeeId = 'fee_tuition_g10_first_term';
  const demoInvoiceId = 'inv_2026_001';

  const memoryStore = {
    tenants: new Map<string, any>(),
    domains: new Map<string, any>(),
    campuses: new Map<string, any>(),
    users: new Map<string, any>(),
    roles: new Map<string, any>(),
    permissions: new Map<string, any>(),
    students: new Map<string, any>(),
    parents: new Map<string, any>(),
    teachers: new Map<string, any>(),
    academicYears: new Map<string, any>(),
    terms: new Map<string, any>(),
    classes: new Map<string, any>(),
    subjects: new Map<string, any>(),
    enrollments: new Map<string, any>(),
    attendance: new Map<string, any>(),
    examinations: new Map<string, any>(),
    results: new Map<string, any>(),
    assessmentStructures: new Map<string, any>(),
    academicSummaries: new Map<string, any>(),
    feeStructures: new Map<string, any>(),
    invoices: new Map<string, any>(),
    payments: new Map<string, any>(),
    payroll: new Map<string, any>(),
    staffSalaryProfiles: new Map<string, any>(),
    expenses: new Map<string, any>(),
    transportRoutes: new Map<string, any>(),
    transportStops: new Map<string, any>(),
    studentTransportAllocations: new Map<string, any>(),
    vehicles: new Map<string, any>(),
    transportTrips: new Map<string, any>(),
    tripBoardingRecords: new Map<string, any>(),
    vehicleGpsLogs: new Map<string, any>(),
    notifications: new Map<string, any>(),
    fileAssets: new Map<string, any>(),
    subscriptions: new Map<string, any>(),
    subscriptionInvoices: new Map<string, any>(),
    auditLogs: new Map<string, any>(),
    timetables: new Map<string, any>(),
    timetableEntries: new Map<string, any>(),
    homework: new Map<string, any>(),
    homeworkSubmissions: new Map<string, any>(),
    communications: new Map<string, any>(),
    communicationThreads: new Map<string, any>(),
    billingInvoices: new Map<string, any>(),
    gradingScales: new Map<string, any>(),
    feeWaivers: new Map<string, any>(),
    classSubjects: new Map<string, any>(),
    mfaSecrets: new Map<string, any>(),
    resetTokens: new Map<string, any>(),
    admissionInquiries: new Map<string, any>(),
    admissionApplications: new Map<string, any>(),
    admissionApplicationDocuments: new Map<string, any>(),
    admissionScreenings: new Map<string, any>(),
    admissionEntranceTests: new Map<string, any>(),
    admissionInterviews: new Map<string, any>(),
    admissionDecisions: new Map<string, any>(),
    admissionOffers: new Map<string, any>(),
    studentLifecycleEvents: new Map<string, any>(),
    promotionBatches: new Map<string, any>(),
    alumniRecords: new Map<string, any>(),
    studentParents: new Map<string, any>(),
    attendanceSessions: new Map<string, any>(),
    attendanceConfigs: new Map<string, any>(),
    attendanceCorrections: new Map<string, any>(),
    truancyIncidents: new Map<string, any>(),
    studyMaterials: new Map<string, any>(),
    syllabusTopics: new Map<string, any>(),
    disciplineIncidents: new Map<string, any>(),
    disciplinaryActions: new Map<string, any>(),
    detentionSessions: new Map<string, any>(),
    detentionAssignments: new Map<string, any>(),
    meritAwards: new Map<string, any>(),
    hostels: new Map<string, any>(),
    hostelRooms: new Map<string, any>(),
    hostelBeds: new Map<string, any>(),
    hostelAllocations: new Map<string, any>(),
    hostelExeats: new Map<string, any>(),
    hostelCurfewSessions: new Map<string, any>(),
    hostelCurfewAttendances: new Map<string, any>(),
    books: new Map<string, any>(),
    bookCopies: new Map<string, any>(),
    bookIssues: new Map<string, any>(),
    bookReservations: new Map<string, any>(),
    libraryFines: new Map<string, any>(),
    vendors: new Map<string, any>(),
    inventoryItems: new Map<string, any>(),
    inventoryStockMovements: new Map<string, any>(),
    schoolAssets: new Map<string, any>(),
    assetDepreciationSchedules: new Map<string, any>(),
    assetMaintenanceLogs: new Map<string, any>(),
    purchaseOrders: new Map<string, any>(),
    purchaseOrderItems: new Map<string, any>(),
    impersonationSessions: new Map<string, any>(),
    dataImportJobs: new Map<string, any>(),
    dataExportJobs: new Map<string, any>(),
    outboxEvents: new Map<string, any>(),
    clinicVisits: new Map<string, any>(),
  };

  memoryStore.tenants.set(demoTenantId, {
    id: demoTenantId,
    name: 'Greenfield International Academy',
    slug: 'greenfield',
    logoUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=200',
    faviconUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=32',
    primaryColor: '#1e3a8a',
    secondaryColor: '#0ea5e9',
    timezone: 'UTC',
    locale: 'en',
    currency: 'USD',
    status: 'ACTIVE',
    plan: 'pro',
    features: {
      attendance: true,
      examinations: true,
      fees: true,
      payroll: true,
      transport: true,
      onlinePayments: true,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
  });

  memoryStore.domains.set('domain_1', {
    id: 'domain_1',
    tenantId: demoTenantId,
    domain: 'greenfield.yoursaas.com',
    type: 'SUBDOMAIN',
    isPrimary: true,
    isVerified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  });

  memoryStore.domains.set('domain_2', {
    id: 'domain_2',
    tenantId: demoTenantId,
    domain: 'greenfieldschool.edu.ng',
    type: 'CUSTOM',
    isPrimary: false,
    isVerified: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  });

  memoryStore.campuses.set(demoCampusId, {
    id: demoCampusId,
    tenantId: demoTenantId,
    name: 'Main Campus',
    code: 'CAMPUS-01',
    address: '14 Education Boulevard',
    city: 'Lagos',
    state: 'Lagos State',
    country: 'Nigeria',
    phone: '+234 801 234 5678',
    email: 'maincampus@greenfield.edu.ng',
    isMain: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  });

  memoryStore.academicYears.set(demoAcademicYearId, {
    id: demoAcademicYearId,
    tenantId: demoTenantId,
    name: '2026/2027 Academic Session',
    startDate: new Date('2026-09-01'),
    endDate: new Date('2027-07-20'),
    isCurrent: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  });

  memoryStore.terms.set(demoTermId, {
    id: demoTermId,
    tenantId: demoTenantId,
    academicYearId: demoAcademicYearId,
    name: 'First Term',
    startDate: new Date('2026-09-01'),
    endDate: new Date('2026-12-18'),
    isCurrent: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  });

  const demoClassesList = [
    {
      id: 'cls_001',
      tenantId: demoTenantId,
      campusId: demoCampusId,
      academicYearId: demoAcademicYearId,
      name: 'JSS 1A',
      gradeLevel: 'JSS 1',
      stream: 'Junior Secondary',
      classTeacher: 'Mr. Obinna Okafor',
      roomLocation: 'Block A, Room 101',
      capacity: 40,
      enrolledCount: 38,
      campus: 'Main Campus',
      status: 'Active',
      subjects: ['English Language', 'General Mathematics', 'Basic Science & Tech', 'Social Studies', 'Civic Education', 'Computer Studies / ICT'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'cls_002',
      tenantId: demoTenantId,
      campusId: demoCampusId,
      academicYearId: demoAcademicYearId,
      name: 'JSS 1B',
      gradeLevel: 'JSS 1',
      stream: 'Junior Secondary',
      classTeacher: 'Mrs. Ngozi Okon',
      roomLocation: 'Block A, Room 102',
      capacity: 40,
      enrolledCount: 36,
      campus: 'Main Campus',
      status: 'Active',
      subjects: ['English Language', 'General Mathematics', 'Basic Science & Tech', 'Social Studies', 'Civic Education', 'Computer Studies / ICT'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'cls_003',
      tenantId: demoTenantId,
      campusId: demoCampusId,
      academicYearId: demoAcademicYearId,
      name: 'JSS 2A',
      gradeLevel: 'JSS 2',
      stream: 'Junior Secondary',
      classTeacher: 'Mr. Tunde Lawal',
      roomLocation: 'Block A, Room 201',
      capacity: 40,
      enrolledCount: 39,
      campus: 'Main Campus',
      status: 'Active',
      subjects: ['English Language', 'General Mathematics', 'Basic Science & Tech', 'Social Studies', 'Civic Education', 'Computer Studies / ICT', 'Agricultural Science'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'cls_004',
      tenantId: demoTenantId,
      campusId: demoCampusId,
      academicYearId: demoAcademicYearId,
      name: 'JSS 2B',
      gradeLevel: 'JSS 2',
      stream: 'Junior Secondary',
      classTeacher: 'Ms. Fatima Bello',
      roomLocation: 'Block A, Room 202',
      capacity: 40,
      enrolledCount: 37,
      campus: 'Main Campus',
      status: 'Active',
      subjects: ['English Language', 'General Mathematics', 'Basic Science & Tech', 'Social Studies', 'Civic Education', 'Computer Studies / ICT', 'Agricultural Science'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'cls_005',
      tenantId: demoTenantId,
      campusId: demoCampusId,
      academicYearId: demoAcademicYearId,
      name: 'JSS 3A',
      gradeLevel: 'JSS 3',
      stream: 'Junior Secondary',
      classTeacher: 'Mr. Chukwuemeka Okoye',
      roomLocation: 'Block A, Room 301',
      capacity: 40,
      enrolledCount: 35,
      campus: 'Main Campus',
      status: 'Active',
      subjects: ['English Language', 'General Mathematics', 'Basic Science & Tech', 'Social Studies', 'Civic Education', 'Computer Studies / ICT', 'Agricultural Science', 'Business Studies'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'cls_006',
      tenantId: demoTenantId,
      campusId: demoCampusId,
      academicYearId: demoAcademicYearId,
      name: 'SSS 1 Science',
      gradeLevel: 'SSS 1',
      stream: 'Senior Sciences',
      classTeacher: 'Dr. Olumide Bakare',
      roomLocation: 'Block B, Lab 1',
      capacity: 35,
      enrolledCount: 32,
      campus: 'Main Campus',
      status: 'Active',
      subjects: ['English Language', 'General Mathematics', 'Physics', 'Chemistry', 'Biology', 'Further Mathematics', 'Computer Studies / ICT'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'cls_007',
      tenantId: demoTenantId,
      campusId: demoCampusId,
      academicYearId: demoAcademicYearId,
      name: 'SSS 1 Art',
      gradeLevel: 'SSS 1',
      stream: 'Senior Arts & Humanities',
      classTeacher: 'Mrs. Folashade Adebayo',
      roomLocation: 'Block B, Room 102',
      capacity: 35,
      enrolledCount: 28,
      campus: 'Main Campus',
      status: 'Active',
      subjects: ['English Language', 'General Mathematics', 'Literature in English', 'Government', 'Economics', 'Civic Education'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'cls_008',
      tenantId: demoTenantId,
      campusId: demoCampusId,
      academicYearId: demoAcademicYearId,
      name: 'SSS 2 Science',
      gradeLevel: 'SSS 2',
      stream: 'Senior Sciences',
      classTeacher: 'Mrs. Nkechi Eze',
      roomLocation: 'Block B, Lab 2',
      capacity: 35,
      enrolledCount: 30,
      campus: 'Main Campus',
      status: 'Active',
      subjects: ['English Language', 'General Mathematics', 'Physics', 'Chemistry', 'Biology', 'Further Mathematics', 'Economics'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'cls_009',
      tenantId: demoTenantId,
      campusId: demoCampusId,
      academicYearId: demoAcademicYearId,
      name: 'SSS 3 Science',
      gradeLevel: 'SSS 3',
      stream: 'Senior Sciences',
      classTeacher: 'Mr. Ibrahim Musa',
      roomLocation: 'Block B, Room 201',
      capacity: 35,
      enrolledCount: 34,
      campus: 'Main Campus',
      status: 'Active',
      subjects: ['English Language', 'General Mathematics', 'Physics', 'Chemistry', 'Biology', 'Further Mathematics', 'Economics'],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  demoClassesList.forEach((cls) => {
    memoryStore.classes.set(cls.id, cls);
  });
  // Backward compatibility reference
  memoryStore.classes.set(demoClassId, demoClassesList[0]);

  const demoSubjectsList = [
    { id: 'sub_math_101', code: 'MTH', name: 'Mathematics', description: 'General Mathematics & Numerical Literacy', isElective: false },
    { id: 'sub_eng_101', code: 'ENG', name: 'English Language', description: 'Grammar, Oral & Literature', isElective: false },
    { id: 'sub_sci_101', code: 'BSC', name: 'Basic Science', description: 'Basic Science & Technology', isElective: false },
    { id: 'sub_phy_201', code: 'PHY', name: 'Physics', description: 'Mechanics, Optics & Electromagnetism', isElective: true },
    { id: 'sub_che_201', code: 'CHM', name: 'Chemistry', description: 'Organic, Inorganic & Physical Chemistry', isElective: true },
    { id: 'sub_bio_201', code: 'BIO', name: 'Biology', description: 'Ecology, Genetics & Physiology', isElective: true },
    { id: 'sub_cmp_101', code: 'CMP', name: 'Computer Studies', description: 'Information & Communications Tech', isElective: false },
    { id: 'sub_ecn_201', code: 'ECN', name: 'Economics', description: 'Microeconomics & Public Finance', isElective: true },
    { id: 'sub_cve_101', code: 'CVE', name: 'Civic Education', description: 'National Values, Ethics & Citizenship', isElective: false },
    { id: 'sub_lit_201', code: 'LIT', name: 'Literature in English', description: 'Prose, Drama & Poetry', isElective: true },
    { id: 'sub_agr_101', code: 'AGR', name: 'Agricultural Science', description: 'Crop Production & Soil Science', isElective: true },
  ];

  demoSubjectsList.forEach((sub) => {
    memoryStore.subjects.set(sub.id, {
      ...sub,
      tenantId: demoTenantId,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  });

  const demoTimetableList = [
    { id: 'slot_001', classLevel: 'JSS 1A', day: 'Monday', periodId: 1, subject: 'Mathematics', teacher: 'Mrs. Folashade Adebayo', room: 'Room 101 (Block A)', notes: 'Algebra intro' },
    { id: 'slot_002', classLevel: 'JSS 1A', day: 'Monday', periodId: 2, subject: 'English Language', teacher: 'Mr. Obinna Okafor', room: 'Room 101 (Block A)', notes: 'Comprehension' },
    { id: 'slot_003', classLevel: 'JSS 1A', day: 'Monday', periodId: 3, subject: 'Basic Science', teacher: 'Mr. Tunde Lawal', room: 'Science Lab 1', notes: 'Lab demo' },
    { id: 'slot_004', classLevel: 'JSS 1A', day: 'Monday', periodId: 4, subject: 'Computer Studies', teacher: 'Mr. Chukwuemeka Okoye', room: 'ICT Innovation Lab', notes: 'Keyboarding' },
    { id: 'slot_005', classLevel: 'JSS 1A', day: 'Monday', periodId: 5, subject: 'Civic Education', teacher: 'Mr. Ayodele Balogun', room: 'Room 101 (Block A)', notes: 'Rights & Duties' },
    { id: 'slot_006', classLevel: 'JSS 1A', day: 'Monday', periodId: 6, subject: 'Agricultural Science', teacher: 'Mr. Tunde Lawal', room: 'Room 101 (Block A)', notes: 'Crop rotation' },
    { id: 'slot_007', classLevel: 'JSS 1A', day: 'Monday', periodId: 7, subject: 'Mathematics', teacher: 'Mrs. Folashade Adebayo', room: 'Room 101 (Block A)', notes: 'Practice exercises' },
    { id: 'slot_008', classLevel: 'JSS 1A', day: 'Tuesday', periodId: 1, subject: 'English Language', teacher: 'Mr. Obinna Okafor', room: 'Room 101 (Block A)', notes: 'Essay writing' },
    { id: 'slot_009', classLevel: 'JSS 1A', day: 'Tuesday', periodId: 2, subject: 'Mathematics', teacher: 'Mrs. Folashade Adebayo', room: 'Room 101 (Block A)', notes: 'Geometry' },
    { id: 'slot_010', classLevel: 'JSS 1A', day: 'Tuesday', periodId: 3, subject: 'Computer Studies', teacher: 'Mr. Chukwuemeka Okoye', room: 'ICT Innovation Lab', notes: 'Practical test' },
    { id: 'slot_011', classLevel: 'JSS 1A', day: 'Tuesday', periodId: 4, subject: 'Basic Science', teacher: 'Mr. Tunde Lawal', room: 'Science Lab 1', notes: 'Living organisms' },
    { id: 'slot_012', classLevel: 'JSS 1A', day: 'Tuesday', periodId: 5, subject: 'Literature in English', teacher: 'Mr. Obinna Okafor', room: 'Room 101 (Block A)', notes: 'Prose reading' },
    { id: 'slot_013', classLevel: 'JSS 1A', day: 'Wednesday', periodId: 1, subject: 'Basic Science', teacher: 'Mr. Tunde Lawal', room: 'Science Lab 1', notes: 'Matter & Energy' },
    { id: 'slot_014', classLevel: 'JSS 1A', day: 'Wednesday', periodId: 2, subject: 'Mathematics', teacher: 'Mrs. Folashade Adebayo', room: 'Room 101 (Block A)', notes: 'Fractions' },
    { id: 'slot_015', classLevel: 'JSS 1A', day: 'Wednesday', periodId: 3, subject: 'English Language', teacher: 'Mr. Obinna Okafor', room: 'Room 101 (Block A)', notes: 'Grammar & Vocab' },
    { id: 'slot_016', classLevel: 'JSS 1A', day: 'Wednesday', periodId: 4, subject: 'Civic Education', teacher: 'Mr. Ayodele Balogun', room: 'Room 101 (Block A)', notes: 'Constitution' },
  ];

  demoTimetableList.forEach((slot) => {
    memoryStore.timetableEntries.set(slot.id, {
      ...slot,
      tenantId: demoTenantId,
      campusId: demoCampusId,
      classId: 'cls_001',
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  });

  memoryStore.users.set(demoOwnerId, {
    id: demoOwnerId,
    tenantId: demoTenantId,
    email: 'admin@greenfield.edu.ng',
    passwordHash: '$2a$10$iIuJ0rK9V8g7dD2C9Xv2UuG0wOaG0j6YtM8aM.Z8eJ6K0pY9jA0yW',
    firstName: 'Dr. Arthur',
    lastName: 'Pendelton',
    phone: '+234 809 111 2233',
    isActive: true,
    isPlatformAdmin: false,
    roles: ['School Owner'],
    permissionIds: [
      'settings.view', 'settings.manage', 'domains.manage', 'subscription.manage',
      'users.view', 'users.create', 'users.update', 'users.delete', 'users.manage',
      'campuses.view', 'campuses.manage', 'students.view', 'students.create', 'students.update', 'students.delete',
      'academics.view', 'academics.manage', 'attendance.view', 'attendance.mark',
      'examinations.manage', 'results.enter', 'results.approve', 'results.publish',
      'fees.view', 'fees.create', 'fees.manage', 'invoices.manage', 'payments.view', 'payments.refund',
      'payroll.manage', 'expenses.manage', 'transport.manage', 'reports.view', 'files.manage', 'audit.view'
    ],
    campusIds: [demoCampusId],
    createdAt: new Date(),
    updatedAt: new Date(),
  });

  memoryStore.students.set(demoStudentId, {
    id: demoStudentId,
    tenantId: demoTenantId,
    campusId: demoCampusId,
    admissionNumber: 'GHS/2024/001',
    firstName: 'Chinedu',
    middleName: 'Emeka',
    lastName: 'Okafor',
    gender: 'Male',
    dateOfBirth: new Date('2012-05-14'),
    classLevel: 'JSS 1A',
    bloodGroup: 'O+',
    genotype: 'AA',
    house: 'Blue Sapphire',
    email: 'chinedu.okafor@student.greenfield.edu.ng',
    phone: '+234 803 111 2222',
    address: '14 Admiralty Way, Lekki Phase 1, Lagos',
    guardianName: 'Mr. Obinna Okafor',
    guardianRelationship: 'Father',
    guardianPhone: '+234 803 111 2222',
    guardianEmail: 'obinna.okafor@example.com',
    guardianAddress: '14 Admiralty Way, Lekki Phase 1, Lagos',
    attendanceRate: '97.2%',
    termAverage: '88.4%',
    termGrade: 'A (Distinction)',
    classPosition: '1st of 38',
    status: 'ACTIVE',
    createdAt: new Date(),
    updatedAt: new Date(),
  });

  const demoStudentId2 = 'std_amina_yusuf_02';
  memoryStore.students.set(demoStudentId2, {
    id: demoStudentId2,
    tenantId: demoTenantId,
    campusId: demoCampusId,
    admissionNumber: 'GHS/2024/002',
    firstName: 'Amina',
    middleName: 'Zainab',
    lastName: 'Yusuf',
    gender: 'Female',
    dateOfBirth: new Date('2011-08-22'),
    classLevel: 'JSS 2A',
    bloodGroup: 'A+',
    genotype: 'AS',
    house: 'Red Ruby',
    email: 'amina.yusuf@student.greenfield.edu.ng',
    phone: '+234 802 333 4444',
    address: '8 Maitama Avenue, Ikoyi, Lagos',
    guardianName: 'Hajiya Fatima Yusuf',
    guardianRelationship: 'Mother',
    guardianPhone: '+234 802 333 4444',
    guardianEmail: 'fatima.yusuf@example.com',
    guardianAddress: '8 Maitama Avenue, Ikoyi, Lagos',
    attendanceRate: '99.1%',
    termAverage: '91.2%',
    termGrade: 'A+ (Honors)',
    classPosition: '1st of 36',
    status: 'ACTIVE',
    createdAt: new Date(),
    updatedAt: new Date(),
  });

  const demoStudentId3 = 'std_tunde_bakare_03';
  memoryStore.students.set(demoStudentId3, {
    id: demoStudentId3,
    tenantId: demoTenantId,
    campusId: demoCampusId,
    admissionNumber: 'GHS/2024/003',
    firstName: 'Tunde',
    middleName: 'Olumide',
    lastName: 'Bakare',
    gender: 'Male',
    dateOfBirth: new Date('2010-11-03'),
    classLevel: 'SSS 1A',
    bloodGroup: 'B+',
    genotype: 'AA',
    house: 'Green Emerald',
    email: 'tunde.bakare@student.greenfield.edu.ng',
    phone: '+234 805 555 6666',
    address: '22 Isaac John Street, GRA Ikeja, Lagos',
    guardianName: 'Engr. Adekunle Bakare',
    guardianRelationship: 'Father',
    guardianPhone: '+234 805 555 6666',
    guardianEmail: 'adekunle.bakare@example.com',
    guardianAddress: '22 Isaac John Street, GRA Ikeja, Lagos',
    attendanceRate: '94.0%',
    termAverage: '76.8%',
    termGrade: 'B (Credit)',
    classPosition: '7th of 40',
    status: 'ACTIVE',
    createdAt: new Date(),
    updatedAt: new Date(),
  });

  const demoStudentId4 = 'std_favour_adeleke_04';
  memoryStore.students.set(demoStudentId4, {
    id: demoStudentId4,
    tenantId: demoTenantId,
    campusId: demoCampusId,
    admissionNumber: 'GHS/2024/004',
    firstName: 'Favour',
    middleName: 'Blessing',
    lastName: 'Adeleke',
    gender: 'Female',
    dateOfBirth: new Date('2013-02-18'),
    classLevel: 'JSS 1B',
    bloodGroup: 'O+',
    genotype: 'AA',
    house: 'Yellow Amber',
    email: 'favour.adeleke@student.greenfield.edu.ng',
    phone: '+234 807 777 8888',
    address: '5 Akin Adesola Street, Victoria Island, Lagos',
    guardianName: 'Mrs. Funmilayo Adeleke',
    guardianRelationship: 'Mother',
    guardianPhone: '+234 807 777 8888',
    guardianEmail: 'funmi.adeleke@example.com',
    guardianAddress: '5 Akin Adesola Street, Victoria Island, Lagos',
    attendanceRate: '96.5%',
    termAverage: '84.0%',
    termGrade: 'B+ (Very Good)',
    classPosition: '3rd of 35',
    status: 'ACTIVE',
    createdAt: new Date(),
    updatedAt: new Date(),
  });

  const additionalStudents = [
    {
      id: 'std_maryam_bello_05',
      admissionNumber: 'GHS/2024/005',
      firstName: 'Maryam',
      middleName: 'Amina',
      lastName: 'Bello',
      gender: 'Female',
      dateOfBirth: new Date('2012-09-12'),
      classLevel: 'JSS 1A',
      currentClassId: 'cls_001',
      bloodGroup: 'A+',
      genotype: 'AA',
      house: 'Blue Sapphire',
      email: 'maryam.bello@student.greenfield.edu.ng',
      phone: '+234 802 111 5555',
      guardianName: 'Alhaji Bashir Bello',
      guardianRelationship: 'Father',
      guardianPhone: '+234 802 111 5555',
      status: 'ACTIVE',
    },
    {
      id: 'std_emeka_eze_06',
      admissionNumber: 'GHS/2024/006',
      firstName: 'Emeka',
      middleName: 'Stanley',
      lastName: 'Eze',
      gender: 'Male',
      dateOfBirth: new Date('2012-07-04'),
      classLevel: 'JSS 1A',
      currentClassId: 'cls_001',
      bloodGroup: 'O+',
      genotype: 'AA',
      house: 'Red Ruby',
      email: 'emeka.eze@student.greenfield.edu.ng',
      phone: '+234 803 222 6666',
      guardianName: 'Chief Stanley Eze',
      guardianRelationship: 'Father',
      guardianPhone: '+234 803 222 6666',
      status: 'ACTIVE',
    },
    {
      id: 'std_zainab_aliyu_07',
      admissionNumber: 'GHS/2024/007',
      firstName: 'Zainab',
      middleName: 'Fatima',
      lastName: 'Aliyu',
      gender: 'Female',
      dateOfBirth: new Date('2012-11-20'),
      classLevel: 'JSS 1A',
      currentClassId: 'cls_001',
      bloodGroup: 'B+',
      genotype: 'AS',
      house: 'Green Emerald',
      email: 'zainab.aliyu@student.greenfield.edu.ng',
      phone: '+234 805 333 7777',
      guardianName: 'Dr. (Mrs) Khadijah Aliyu',
      guardianRelationship: 'Mother',
      guardianPhone: '+234 805 333 7777',
      status: 'ACTIVE',
    },
    {
      id: 'std_damilola_adeleke_08',
      admissionNumber: 'GHS/2024/008',
      firstName: 'Damilola',
      middleName: 'Samuel',
      lastName: 'Adeleke',
      gender: 'Male',
      dateOfBirth: new Date('2012-04-15'),
      classLevel: 'JSS 1A',
      currentClassId: 'cls_001',
      bloodGroup: 'A+',
      genotype: 'AA',
      house: 'Yellow Amber',
      email: 'damilola.adeleke@student.greenfield.edu.ng',
      phone: '+234 807 444 8888',
      guardianName: 'Mr. Olawale Adeleke',
      guardianRelationship: 'Father',
      guardianPhone: '+234 807 444 8888',
      status: 'ACTIVE',
    },
    {
      id: 'std_hauwa_sanusi_09',
      admissionNumber: 'GHS/2024/009',
      firstName: 'Hauwa',
      middleName: 'Khadija',
      lastName: 'Sanusi',
      gender: 'Female',
      dateOfBirth: new Date('2012-12-01'),
      classLevel: 'JSS 1A',
      currentClassId: 'cls_001',
      bloodGroup: 'O+',
      genotype: 'AA',
      house: 'Blue Sapphire',
      email: 'hauwa.sanusi@student.greenfield.edu.ng',
      phone: '+234 808 555 9999',
      guardianName: 'Mallam Sanusi Lamido',
      guardianRelationship: 'Father',
      guardianPhone: '+234 808 555 9999',
      status: 'ACTIVE',
    },
    {
      id: 'std_david_nwachukwu_10',
      admissionNumber: 'GHS/2024/010',
      firstName: 'David',
      middleName: 'Chibuike',
      lastName: 'Nwachukwu',
      gender: 'Male',
      dateOfBirth: new Date('2012-08-30'),
      classLevel: 'JSS 1A',
      currentClassId: 'cls_001',
      bloodGroup: 'O-',
      genotype: 'AA',
      house: 'Red Ruby',
      email: 'david.nwachukwu@student.greenfield.edu.ng',
      phone: '+234 809 666 0000',
      guardianName: 'Mrs. Ngozi Nwachukwu',
      guardianRelationship: 'Mother',
      guardianPhone: '+234 809 666 0000',
      status: 'ACTIVE',
    },
  ];

  additionalStudents.forEach((st) => {
    memoryStore.students.set(st.id, {
      ...st,
      tenantId: demoTenantId,
      campusId: demoCampusId,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  });

  // Seed Initial Attendance Records for Today
  const todayStr = new Date().toISOString().split('T')[0];
  const demoAttendanceSeeds = [
    { studentId: demoStudentId, status: 'PRESENT', time: '07:45 AM', remarks: '' },
    { studentId: 'std_maryam_bello_05', status: 'PRESENT', time: '07:40 AM', remarks: '' },
    { studentId: 'std_emeka_eze_06', status: 'LATE', time: '08:15 AM', remarks: 'Traffic congestion on Lekki Tollway' },
    { studentId: 'std_zainab_aliyu_07', status: 'PRESENT', time: '07:50 AM', remarks: '' },
    { studentId: 'std_damilola_adeleke_08', status: 'ABSENT', time: 'N/A', remarks: 'Malaria fever / doctor sick note submitted' },
    { studentId: 'std_hauwa_sanusi_09', status: 'PRESENT', time: '07:35 AM', remarks: '' },
    { studentId: 'std_david_nwachukwu_10', status: 'EXCUSED', time: 'N/A', remarks: 'State school debate tournament' },
  ];

  demoAttendanceSeeds.forEach((att, idx) => {
    const attId = `att_seed_${todayStr}_${idx + 1}`;
    memoryStore.attendance.set(attId, {
      id: attId,
      tenantId: demoTenantId,
      campusId: demoCampusId,
      studentId: att.studentId,
      classId: 'cls_001',
      sessionType: 'DAILY',
      date: new Date(`${todayStr}T08:00:00.000Z`),
      status: att.status,
      method: 'MANUAL',
      checkInTime: att.time !== 'N/A' ? new Date(`${todayStr}T${att.time === '07:45 AM' ? '07:45' : att.time === '07:40 AM' ? '07:40' : att.time === '08:15 AM' ? '08:15' : att.time === '07:50 AM' ? '07:50' : '07:35'}:00.000Z`) : null,
      remarks: att.remarks,
      markedByUserId: demoOwnerId,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  });

  // Seed Recent 5-Day Attendance History for Demo Student 1 (Chinedu Okafor)
  const historyDates = [
    { offsetDays: 1, status: 'PRESENT', time: '07:42 AM', remarks: '' },
    { offsetDays: 2, status: 'PRESENT', time: '07:48 AM', remarks: '' },
    { offsetDays: 3, status: 'LATE', time: '08:10 AM', remarks: 'Heavy morning rainfall' },
    { offsetDays: 4, status: 'PRESENT', time: '07:39 AM', remarks: '' },
    { offsetDays: 5, status: 'PRESENT', time: '07:44 AM', remarks: '' },
  ];

  historyDates.forEach((h) => {
    const d = new Date();
    d.setDate(d.getDate() - h.offsetDays);
    const dateStr = d.toISOString().split('T')[0];
    const attId = `att_hist_std1_${dateStr}`;
    memoryStore.attendance.set(attId, {
      id: attId,
      tenantId: demoTenantId,
      campusId: demoCampusId,
      studentId: demoStudentId,
      classId: 'cls_001',
      sessionType: 'DAILY',
      date: new Date(`${dateStr}T08:00:00.000Z`),
      status: h.status,
      method: 'MANUAL',
      checkInTime: new Date(`${dateStr}T07:45:00.000Z`),
      remarks: h.remarks,
      markedByUserId: demoOwnerId,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  });

  // Seed Examinations Cycles & Exam Papers
  const demoExamCycles = [
    {
      id: 'cycle_001',
      tenantId: demoTenantId,
      campusId: demoCampusId,
      academicYearId: demoAcademicYearId,
      termId: demoTermId,
      title: 'First Term Terminal Examination',
      name: 'First Term Terminal Examination',
      examType: 'Terminal Examination',
      session: '2024/2025',
      term: 'First Term',
      startDate: new Date('2024-11-25'),
      endDate: new Date('2024-12-06'),
      status: 'Scheduled',
      registeredCandidates: 540,
      hallCount: 4,
      papersCount: 5,
      moderationProgress: 0,
      instructions: 'All candidates must arrive 20 minutes prior to paper commencement with valid exam passes.',
      isPublished: false,
      papers: [
        {
          id: 'paper_001',
          examCycleId: 'cycle_001',
          subject: 'Mathematics',
          paperCode: 'MTH-101',
          classLevel: 'JSS 1',
          date: '2024-11-25',
          startTime: '09:00 AM',
          endTime: '11:30 AM',
          duration: '2h 30m',
          hall: 'Main Examination Hall (Block A)',
          invigilator: 'Dr. Olumide Bakare',
          maxScore: 100,
          status: 'Draft',
        },
        {
          id: 'paper_002',
          examCycleId: 'cycle_001',
          subject: 'English Language',
          paperCode: 'ENG-101',
          classLevel: 'JSS 1',
          date: '2024-11-26',
          startTime: '09:00 AM',
          endTime: '11:00 AM',
          duration: '2h 00m',
          hall: 'Main Examination Hall (Block A)',
          invigilator: 'Mrs. Folashade Adebayo',
          maxScore: 100,
          status: 'Draft',
        },
        {
          id: 'paper_003',
          examCycleId: 'cycle_001',
          subject: 'Basic Science & Tech',
          paperCode: 'BST-101',
          classLevel: 'JSS 1',
          date: '2024-11-27',
          startTime: '09:00 AM',
          endTime: '11:00 AM',
          duration: '2h 00m',
          hall: 'Science Auditorium (Block B)',
          invigilator: 'Mrs. Nkechi Eze',
          maxScore: 100,
          status: 'Draft',
        },
        {
          id: 'paper_004',
          examCycleId: 'cycle_001',
          subject: 'Computer Studies / ICT',
          paperCode: 'ICT-101',
          classLevel: 'JSS 1',
          date: '2024-11-28',
          startTime: '09:00 AM',
          endTime: '11:00 AM',
          duration: '2h 00m',
          hall: 'ICT Innovation Center (CBT Lab)',
          invigilator: 'Mr. Chukwuemeka Okoye',
          maxScore: 100,
          status: 'Draft',
        },
        {
          id: 'paper_005',
          examCycleId: 'cycle_001',
          subject: 'Civic Education',
          paperCode: 'CVE-101',
          classLevel: 'JSS 1',
          date: '2024-11-29',
          startTime: '09:00 AM',
          endTime: '10:30 AM',
          duration: '1h 30m',
          hall: 'Main Examination Hall (Block A)',
          invigilator: 'Mr. Obinna Okafor',
          maxScore: 100,
          status: 'Draft',
        },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'cycle_002',
      tenantId: demoTenantId,
      campusId: demoCampusId,
      academicYearId: demoAcademicYearId,
      termId: demoTermId,
      title: 'Mid-Term Continuous Assessment Series',
      name: 'Mid-Term Continuous Assessment Series',
      examType: 'Continuous Assessment (Mid-Term)',
      session: '2024/2025',
      term: 'First Term',
      startDate: new Date('2024-10-14'),
      endDate: new Date('2024-10-18'),
      status: 'Published / Completed',
      registeredCandidates: 540,
      hallCount: 3,
      papersCount: 2,
      moderationProgress: 100,
      instructions: 'CA test papers administered during normal period slots.',
      isPublished: true,
      papers: [
        {
          id: 'paper_006',
          examCycleId: 'cycle_002',
          subject: 'Mathematics',
          paperCode: 'MTH-CA1',
          classLevel: 'JSS 1',
          date: '2024-10-14',
          startTime: '08:30 AM',
          endTime: '09:30 AM',
          duration: '1h 00m',
          hall: 'Classrooms',
          invigilator: 'Class Teachers',
          maxScore: 20,
          status: 'Published',
        },
        {
          id: 'paper_007',
          examCycleId: 'cycle_002',
          subject: 'English Language',
          paperCode: 'ENG-CA1',
          classLevel: 'JSS 1',
          date: '2024-10-15',
          startTime: '08:30 AM',
          endTime: '09:30 AM',
          duration: '1h 00m',
          hall: 'Classrooms',
          invigilator: 'Class Teachers',
          maxScore: 20,
          status: 'Published',
        },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'cycle_003',
      tenantId: demoTenantId,
      campusId: demoCampusId,
      academicYearId: demoAcademicYearId,
      termId: demoTermId,
      title: 'Senior School Mock WASSCE Examination',
      name: 'Senior School Mock WASSCE Examination',
      examType: 'Mock Examination (WASSCE / NECO)',
      session: '2024/2025',
      term: 'First Term',
      startDate: new Date('2024-11-18'),
      endDate: new Date('2024-11-29'),
      status: 'In Progress',
      registeredCandidates: 165,
      hallCount: 2,
      papersCount: 0,
      moderationProgress: 45,
      instructions: 'Standard WAEC examination regulations apply strictly in all testing halls.',
      isPublished: false,
      papers: [],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  demoExamCycles.forEach((cycle) => {
    memoryStore.examinations.set(cycle.id, cycle);
  });

  // Seed Grading Scales
  const demoGradingScales = [
    {
      id: 'scale_waec',
      tenantId: demoTenantId,
      name: 'WAEC / WASSCE Standard 9-Point Scale',
      code: 'WAEC_9P',
      description: 'Standard West African Examinations Council grading scale used for Senior Secondary.',
      division: 'Senior Secondary (SSS 1 - SSS 3)',
      passThreshold: 50,
      bands: [
        { id: 'b1', symbol: 'A1', minScore: 75, maxScore: 100, gradePoint: 4.0, remark: 'Excellent / Distinction', badgeColor: 'text-emerald-700 bg-emerald-50 border-emerald-200' },
        { id: 'b2', symbol: 'B2', minScore: 70, maxScore: 74, gradePoint: 3.6, remark: 'Very Good', badgeColor: 'text-emerald-600 bg-emerald-50 border-emerald-200' },
        { id: 'b3', symbol: 'B3', minScore: 65, maxScore: 69, gradePoint: 3.2, remark: 'Good', badgeColor: 'text-teal-700 bg-teal-50 border-teal-200' },
        { id: 'b4', symbol: 'C4', minScore: 60, maxScore: 64, gradePoint: 2.8, remark: 'Credit (High)', badgeColor: 'text-indigo-700 bg-indigo-50 border-indigo-200' },
        { id: 'b5', symbol: 'C5', minScore: 55, maxScore: 59, gradePoint: 2.4, remark: 'Credit (Middle)', badgeColor: 'text-indigo-600 bg-indigo-50 border-indigo-200' },
        { id: 'b6', symbol: 'C6', minScore: 50, maxScore: 54, gradePoint: 2.0, remark: 'Credit (Pass)', badgeColor: 'text-blue-700 bg-blue-50 border-blue-200' },
        { id: 'b7', symbol: 'D7', minScore: 45, maxScore: 49, gradePoint: 1.6, remark: 'Pass (Weak)', badgeColor: 'text-amber-700 bg-amber-50 border-amber-200' },
        { id: 'b8', symbol: 'E8', minScore: 40, maxScore: 44, gradePoint: 1.2, remark: 'Pass (Marginal)', badgeColor: 'text-orange-700 bg-orange-50 border-orange-200' },
        { id: 'b9', symbol: 'F9', minScore: 0, maxScore: 39, gradePoint: 0.0, remark: 'Fail', badgeColor: 'text-rose-700 bg-rose-50 border-rose-200' },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'scale_igcse',
      tenantId: demoTenantId,
      name: 'Cambridge / IGCSE International Scale',
      code: 'CAMBRIDGE_IGCSE',
      description: 'International GCSE 8-band alphabetical scale with distinction stars.',
      division: 'International Section & Senior Secondary',
      passThreshold: 50,
      bands: [
        { id: 'ig1', symbol: 'A*', minScore: 90, maxScore: 100, gradePoint: 4.0, remark: 'Outstanding Distinction', badgeColor: 'text-emerald-700 bg-emerald-50 border-emerald-200' },
        { id: 'ig2', symbol: 'A', minScore: 80, maxScore: 89, gradePoint: 3.8, remark: 'Excellent Mastery', badgeColor: 'text-emerald-600 bg-emerald-50 border-emerald-200' },
        { id: 'ig3', symbol: 'B', minScore: 70, maxScore: 79, gradePoint: 3.0, remark: 'Very Good', badgeColor: 'text-indigo-700 bg-indigo-50 border-indigo-200' },
        { id: 'ig4', symbol: 'C', minScore: 60, maxScore: 69, gradePoint: 2.0, remark: 'Good / Competent', badgeColor: 'text-blue-700 bg-blue-50 border-blue-200' },
        { id: 'ig5', symbol: 'D', minScore: 50, maxScore: 59, gradePoint: 1.0, remark: 'Satisfactory Pass', badgeColor: 'text-amber-700 bg-amber-50 border-amber-200' },
        { id: 'ig6', symbol: 'E', minScore: 40, maxScore: 49, gradePoint: 0.5, remark: 'Marginal Pass', badgeColor: 'text-orange-700 bg-orange-50 border-orange-200' },
        { id: 'ig7', symbol: 'U', minScore: 0, maxScore: 39, gradePoint: 0.0, remark: 'Ungraded / Fail', badgeColor: 'text-rose-700 bg-rose-50 border-rose-200' },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'scale_gpa4',
      tenantId: demoTenantId,
      name: 'Standard 4.0 GPA Academic Scale',
      code: 'STANDARD_GPA4',
      description: 'Universal collegiate & secondary 5-tier GPA rubric.',
      division: 'Junior & Senior Secondary',
      passThreshold: 60,
      bands: [
        { id: 'gp1', symbol: 'A', minScore: 80, maxScore: 100, gradePoint: 4.0, remark: 'Superior / High Honors', badgeColor: 'text-emerald-700 bg-emerald-50 border-emerald-200' },
        { id: 'gp2', symbol: 'B', minScore: 70, maxScore: 79, gradePoint: 3.0, remark: 'Above Average', badgeColor: 'text-indigo-700 bg-indigo-50 border-indigo-200' },
        { id: 'gp3', symbol: 'C', minScore: 60, maxScore: 69, gradePoint: 2.0, remark: 'Average / Competent', badgeColor: 'text-blue-700 bg-blue-50 border-blue-200' },
        { id: 'gp4', symbol: 'D', minScore: 50, maxScore: 59, gradePoint: 1.0, remark: 'Below Average Pass', badgeColor: 'text-amber-700 bg-amber-50 border-amber-200' },
        { id: 'gp5', symbol: 'F', minScore: 0, maxScore: 49, gradePoint: 0.0, remark: 'Failure', badgeColor: 'text-rose-700 bg-rose-50 border-rose-200' },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'scale_primary',
      tenantId: demoTenantId,
      name: 'Primary Competency Rubric',
      code: 'PRIMARY_COMP',
      description: 'Descriptive formative assessment scale for early years and primary school.',
      division: 'Primary & Early Years (Year 1 - Year 6)',
      passThreshold: 50,
      bands: [
        { id: 'pr1', symbol: 'Mastery', minScore: 90, maxScore: 100, gradePoint: 4.0, remark: 'Exceeds Expectations consistently', badgeColor: 'text-emerald-700 bg-emerald-50 border-emerald-200' },
        { id: 'pr2', symbol: 'Advanced', minScore: 80, maxScore: 89, gradePoint: 3.5, remark: 'Demonstrates strong understanding', badgeColor: 'text-teal-700 bg-teal-50 border-teal-200' },
        { id: 'pr3', symbol: 'Proficient', minScore: 65, maxScore: 79, gradePoint: 3.0, remark: 'Meets curriculum benchmark', badgeColor: 'text-indigo-700 bg-indigo-50 border-indigo-200' },
        { id: 'pr4', symbol: 'Developing', minScore: 50, maxScore: 64, gradePoint: 2.0, remark: 'Approaching standard with support', badgeColor: 'text-amber-700 bg-amber-50 border-amber-200' },
        { id: 'pr5', symbol: 'Emerging', minScore: 0, maxScore: 49, gradePoint: 1.0, remark: 'Requires intensive intervention', badgeColor: 'text-rose-700 bg-rose-50 border-rose-200' },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  demoGradingScales.forEach((scale) => {
    memoryStore.gradingScales.set(scale.id, scale);
  });

  // Seed Assessment Structures / Rubric Profiles
  const demoAssessmentStructures = [
    {
      id: 'rubric_junior',
      tenantId: demoTenantId,
      name: 'Junior Secondary Standard Rubric',
      code: 'JSS_STANDARD',
      division: 'Junior Secondary (JSS 1 - JSS 3)',
      description: '40% Continuous Assessment combined with 60% Terminal Examination.',
      isDefault: true,
      totalWeight: 100,
      components: [
        { name: 'Continuous Assessment 1 (CA 1)', code: 'CA1', maxRawScore: 20, weight: 20, weightPercentage: 20 },
        { name: 'Continuous Assessment 2 / Mid-Term (CA 2)', code: 'CA2', maxRawScore: 20, weight: 20, weightPercentage: 20 },
        { name: 'Terminal Examination', code: 'EXAM', maxRawScore: 60, weight: 60, weightPercentage: 60 },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'rubric_senior',
      tenantId: demoTenantId,
      name: 'Senior Secondary WAEC Alignment Rubric',
      code: 'SSS_WAEC',
      division: 'Senior Secondary (SSS 1 - SSS 3)',
      description: '30% CA (Tests & Project) combined with 70% Terminal Examination.',
      isDefault: false,
      totalWeight: 100,
      components: [
        { name: 'First CA Test', code: 'CA1', maxRawScore: 15, weight: 15, weightPercentage: 15 },
        { name: 'Second CA Test', code: 'CA2', maxRawScore: 15, weight: 15, weightPercentage: 15 },
        { name: 'Terminal Examination', code: 'EXAM', maxRawScore: 70, weight: 70, weightPercentage: 70 },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  demoAssessmentStructures.forEach((struct) => {
    memoryStore.assessmentStructures.set(struct.id, struct);
  });

  // Seed Fee Structures
  const demoFeeStructures = [
    {
      id: 'fee_junior_tuition',
      tenantId: demoTenantId,
      campusId: demoCampusId,
      academicYearId: demoAcademicYearId,
      termId: demoTermId,
      name: 'Junior Secondary Comprehensive Fee',
      code: 'JSS_COMP',
      amount: 120000,
      currency: 'NGN',
      dueDate: new Date('2025-09-15'),
      applicableGradeLevel: 'JSS 1 - JSS 3',
      targetAudience: 'ALL',
      items: [
        { name: 'Tuition Fee', code: 'TUIT', amount: 80000, isOptional: false },
        { name: 'Development Levy', code: 'DEV', amount: 20000, isOptional: false },
        { name: 'ICT & Lab Access', code: 'ICT', amount: 15000, isOptional: false },
        { name: 'Sports & Uniform', code: 'SPT', amount: 5000, isOptional: false },
      ],
      createdAt: new Date(),
    },
    {
      id: 'fee_senior_tuition',
      tenantId: demoTenantId,
      campusId: demoCampusId,
      academicYearId: demoAcademicYearId,
      termId: demoTermId,
      name: 'Senior Secondary Tuition & WAEC Fee',
      code: 'SSS_COMP',
      amount: 150000,
      currency: 'NGN',
      dueDate: new Date('2025-09-30'),
      applicableGradeLevel: 'SSS 1 - SSS 3',
      targetAudience: 'ALL',
      items: [
        { name: 'Senior Tuition', code: 'TUIT', amount: 100000, isOptional: false },
        { name: 'WAEC Exam Deposit', code: 'WAEC', amount: 30000, isOptional: false },
        { name: 'Science Lab Consumables', code: 'LAB', amount: 20000, isOptional: false },
      ],
      createdAt: new Date(),
    },
    {
      id: 'fee_boarding',
      tenantId: demoTenantId,
      campusId: demoCampusId,
      academicYearId: demoAcademicYearId,
      termId: demoTermId,
      name: 'Termly Boarding & Residence Fee',
      code: 'BOARDING',
      amount: 80000,
      currency: 'NGN',
      dueDate: new Date('2025-09-15'),
      applicableGradeLevel: 'All Grades',
      targetAudience: 'BOARDING',
      items: [
        { name: 'Hostel Accommodation', code: 'HST', amount: 50000, isOptional: false },
        { name: 'Dining & Catering', code: 'DIN', amount: 30000, isOptional: false },
      ],
      createdAt: new Date(),
    },
  ];

  demoFeeStructures.forEach((fee) => {
    memoryStore.feeStructures.set(fee.id, fee);
  });

  // Seed Invoices
  const demoInvoices = [
    {
      id: 'inv_2026_001',
      tenantId: demoTenantId,
      campusId: demoCampusId,
      studentId: demoStudentId,
      feeStructureId: 'fee_junior_tuition',
      invoiceNumber: 'INV-2025-001',
      totalAmount: 120000,
      paidAmount: 120000,
      balanceAmount: 0,
      dueDate: new Date('2025-09-15'),
      status: 'PAID',
      termId: 'First Term 2025/2026',
      currency: 'NGN',
      lineItems: [
        { name: 'Tuition Fee', amount: 80000 },
        { name: 'Development Levy', amount: 20000 },
        { name: 'ICT & Lab Access', amount: 15000 },
        { name: 'Sports & Uniform', amount: 5000 },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'inv_2026_002',
      tenantId: demoTenantId,
      campusId: demoCampusId,
      studentId: 'std_005',
      feeStructureId: 'fee_junior_tuition',
      invoiceNumber: 'INV-2025-002',
      totalAmount: 120000,
      paidAmount: 70000,
      balanceAmount: 50000,
      dueDate: new Date('2025-09-20'),
      status: 'PARTIALLY_PAID',
      termId: 'First Term 2025/2026',
      currency: 'NGN',
      lineItems: [
        { name: 'Tuition Fee', amount: 80000 },
        { name: 'Development Levy', amount: 20000 },
        { name: 'ICT & Lab Access', amount: 15000 },
        { name: 'Sports & Uniform', amount: 5000 },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'inv_2026_003',
      tenantId: demoTenantId,
      campusId: demoCampusId,
      studentId: 'std_006',
      feeStructureId: 'fee_senior_tuition',
      invoiceNumber: 'INV-2025-003',
      totalAmount: 150000,
      paidAmount: 0,
      balanceAmount: 150000,
      dueDate: new Date('2025-09-30'),
      status: 'PENDING',
      termId: 'First Term 2025/2026',
      currency: 'NGN',
      lineItems: [
        { name: 'Senior Tuition', amount: 100000 },
        { name: 'WAEC Exam Deposit', amount: 30000 },
        { name: 'Science Lab Consumables', amount: 20000 },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'inv_2026_004',
      tenantId: demoTenantId,
      campusId: demoCampusId,
      studentId: 'std_007',
      feeStructureId: 'fee_senior_tuition',
      invoiceNumber: 'INV-2025-004',
      totalAmount: 145000,
      paidAmount: 145000,
      balanceAmount: 0,
      dueDate: new Date('2025-09-12'),
      status: 'PAID',
      termId: 'First Term 2025/2026',
      currency: 'NGN',
      lineItems: [
        { name: 'Senior Tuition', amount: 95000 },
        { name: 'Development Levy', amount: 25000 },
        { name: 'Boarding & Laundry Deposit', amount: 25000 },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 'inv_2026_005',
      tenantId: demoTenantId,
      campusId: demoCampusId,
      studentId: 'std_008',
      feeStructureId: 'fee_senior_tuition',
      invoiceNumber: 'INV-2025-005',
      totalAmount: 165000,
      paidAmount: 85000,
      balanceAmount: 80000,
      dueDate: new Date('2025-09-25'),
      status: 'PARTIALLY_PAID',
      termId: 'First Term 2025/2026',
      currency: 'NGN',
      lineItems: [
        { name: 'Final Year Tuition', amount: 110000 },
        { name: 'Graduation & Valedictory', amount: 35000 },
        { name: 'Library & Archive', amount: 20000 },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ];

  demoInvoices.forEach((inv) => {
    memoryStore.invoices.set(inv.id, inv);
  });

  // Seed Payments
  const demoPayments = [
    {
      id: 'pmt_001',
      tenantId: demoTenantId,
      reference: 'PAY-99210',
      studentId: demoStudentId,
      invoiceId: 'inv_2026_001',
      amount: 120000,
      currency: 'NGN',
      provider: 'Paystack (Online)',
      channel: 'Mastercard (Debit)',
      status: 'SUCCESSFUL',
      payerName: 'Mr. Chukwuma Okafor',
      payerEmail: 'c.okafor@gmail.com',
      paidAt: new Date('2025-09-02'),
      createdAt: new Date('2025-09-02'),
    },
    {
      id: 'pmt_002',
      tenantId: demoTenantId,
      reference: 'PAY-99211',
      studentId: 'std_006',
      invoiceId: 'inv_2026_003',
      amount: 50000,
      currency: 'NGN',
      provider: 'Direct Bank Transfer',
      channel: 'NIBSS Instant Payment',
      status: 'SUCCESSFUL',
      payerName: 'Mrs. Folashade Adebayo',
      payerEmail: 'fola.adebayo@yahoo.com',
      paidAt: new Date('2025-09-08'),
      createdAt: new Date('2025-09-08'),
    },
    {
      id: 'pmt_003',
      tenantId: demoTenantId,
      reference: 'PAY-99212',
      studentId: 'std_005',
      invoiceId: 'inv_2026_002',
      amount: 70000,
      currency: 'NGN',
      provider: 'Flutterwave (Card)',
      channel: 'Visa (Debit)',
      status: 'SUCCESSFUL',
      payerName: 'Alhaji Bello Yusuf',
      payerEmail: 'bello.yusuf@kware.ng',
      paidAt: new Date('2025-09-05'),
      createdAt: new Date('2025-09-05'),
    },
    {
      id: 'pmt_004',
      tenantId: demoTenantId,
      reference: 'PAY-99213',
      studentId: 'std_007',
      invoiceId: 'inv_2026_004',
      amount: 145000,
      currency: 'NGN',
      provider: 'Paystack (Online)',
      channel: 'USSD (*737#)',
      status: 'SUCCESSFUL',
      payerName: 'Dr. K. Eze',
      payerEmail: 'k.eze@zenithbank.com',
      paidAt: new Date('2025-09-03'),
      createdAt: new Date('2025-09-03'),
    },
    {
      id: 'pmt_005',
      tenantId: demoTenantId,
      reference: 'PAY-99214',
      studentId: 'std_008',
      invoiceId: 'inv_2026_005',
      amount: 85000,
      currency: 'NGN',
      provider: 'Campus POS Terminal',
      channel: 'Stanbic POS Terminal 02',
      status: 'SUCCESSFUL',
      payerName: 'Chief Nwosu',
      payerEmail: 'nwosu.logistics@gmail.com',
      paidAt: new Date('2025-09-08'),
      createdAt: new Date('2025-09-08'),
    },
  ];

  demoPayments.forEach((pmt) => {
    memoryStore.payments.set(pmt.id, pmt);
  });

  // Seed Teachers / Staff
  const demoTeacher1 = {
    id: "stf_001",
    tenantId: demoTenantId,
    campusId: demoCampusId,
    employeeNumber: "EMP-2021-004",
    employeeId: "EMP-2021-004",
    firstName: "Kenneth",
    lastName: "Eze",
    fullName: "Dr. Kenneth Eze",
    email: "kenneth.eze@greenfieldhigh.edu.ng",
    phone: "+234 803 444 5555",
    department: "Administration",
    role: "Vice Principal (Academics)",
    qualification: "Ph.D / M.Ed Educational Admin",
    specialization: "Physics & Educational Leadership",
    status: "Active",
    isActive: true,
    dateJoined: "2021-08-15",
    campus: "Main Campus",
    subjectsTaught: ["Senior Physics (SSS 3)"],
    assignedClass: "N/A (Executive Admin)",
    officeLocation: "Admin Block, Suite 201",
    createdAt: new Date(),
    updatedAt: new Date(),
  };
  memoryStore.teachers.set(demoTeacher1.id, demoTeacher1);

  const demoTeacher2 = {
    id: "stf_002",
    tenantId: demoTenantId,
    campusId: demoCampusId,
    employeeNumber: "EMP-2022-019",
    employeeId: "EMP-2022-019",
    firstName: "Folashade",
    lastName: "Adebayo",
    fullName: "Mrs. Folashade Adebayo",
    email: "folashade.a@greenfieldhigh.edu.ng",
    phone: "+234 805 555 6666",
    department: "Mathematics",
    role: "Head of Department (HOD)",
    qualification: "M.Sc Applied Mathematics",
    specialization: "Calculus & Further Math",
    status: "Active",
    isActive: true,
    dateJoined: "2022-01-10",
    campus: "Main Campus",
    subjectsTaught: ["Further Mathematics (SSS 1-3)", "General Math (SSS 2A)"],
    assignedClass: "SSS 2A (Form Tutor)",
    officeLocation: "Math Block, Room 104",
    createdAt: new Date(),
    updatedAt: new Date(),
  };
  memoryStore.teachers.set(demoTeacher2.id, demoTeacher2);

  const demoTeacher3 = {
    id: "stf_003",
    tenantId: demoTenantId,
    campusId: demoCampusId,
    employeeNumber: "EMP-2023-042",
    employeeId: "EMP-2023-042",
    firstName: "Babatunde",
    lastName: "Fashola",
    fullName: "Mr. Babatunde Fashola",
    email: "babatunde.f@greenfieldhigh.edu.ng",
    phone: "+234 802 777 8888",
    department: "Sciences",
    role: "Senior Teacher",
    qualification: "B.Sc Chemistry / PGDE",
    specialization: "Organic & Physical Chemistry",
    status: "Active",
    isActive: true,
    dateJoined: "2023-09-01",
    campus: "Main Campus",
    subjectsTaught: ["Chemistry (SSS 1-3)"],
    assignedClass: "SSS 1A (Assistant Form Tutor)",
    officeLocation: "Science Complex, Lab 2",
    createdAt: new Date(),
    updatedAt: new Date(),
  };
  memoryStore.teachers.set(demoTeacher3.id, demoTeacher3);

  // Seed Parents / Guardians
  const demoParent1 = {
    id: "prt_001",
    tenantId: demoTenantId,
    firstName: "Obinna",
    lastName: "Okafor",
    fullName: "Mr. Obinna Okafor",
    email: "obinna.okafor@example.com",
    phone: "+234 803 111 2222",
    relationship: "Father",
    occupation: "Senior Software Director",
    address: "14 Admiralty Way, Lekki Phase 1, Lagos",
    portalAccess: "Active",
    linkedWards: [
      { id: "std_001", name: "Chinedu Okafor", classLevel: "JSS 1A", admissionNumber: "GHS/2024/001" },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  };
  memoryStore.parents.set(demoParent1.id, demoParent1);

  const demoParent2 = {
    id: "prt_002",
    tenantId: demoTenantId,
    firstName: "Fatima",
    lastName: "Yusuf",
    fullName: "Hajiya Fatima Yusuf",
    email: "fatima.yusuf@example.com",
    phone: "+234 802 333 4444",
    relationship: "Mother",
    occupation: "Legal Consultant",
    address: "8 Maitama Avenue, Ikoyi, Lagos",
    portalAccess: "Active",
    linkedWards: [
      { id: "std_002", name: "Amina Yusuf", classLevel: "JSS 2A", admissionNumber: "GHS/2024/002" },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  };
  memoryStore.parents.set(demoParent2.id, demoParent2);

  const demoParent3 = {
    id: "prt_003",
    tenantId: demoTenantId,
    firstName: "Adekunle",
    lastName: "Bakare",
    fullName: "Engr. Adekunle Bakare",
    email: "adekunle.bakare@example.com",
    phone: "+234 805 555 6666",
    relationship: "Father",
    occupation: "Civil Engineering Contractor",
    address: "22 Isaac John Street, GRA Ikeja, Lagos",
    portalAccess: "Active",
    linkedWards: [
      { id: "std_003", name: "Tunde Bakare", classLevel: "SSS 1A", admissionNumber: "GHS/2024/003" },
    ],
    createdAt: new Date(),
    updatedAt: new Date(),
  };
  memoryStore.parents.set(demoParent3.id, demoParent3);

  // Seed Additional Staff (ICT Coordinator & Health Matron)
  const demoTeacher4 = {
    id: "stf_004",
    tenantId: demoTenantId,
    campusId: demoCampusId,
    employeeNumber: "EMP-2023-088",
    employeeId: "EMP-2023-088",
    firstName: "Tunde",
    lastName: "Lawal",
    fullName: "Mr. Tunde Lawal",
    email: "tunde.lawal@greenfieldhigh.edu.ng",
    phone: "+234 809 111 2233",
    department: "Technology",
    role: "ICT Coordinator",
    qualification: "B.Sc Computer Science / CCNA",
    specialization: "Networking & Computer Studies",
    status: "Active",
    isActive: true,
    dateJoined: "2023-01-15",
    campus: "Main Campus",
    subjectsTaught: ["Computer Studies (JSS 1-3)", "Data Processing (SSS 1-3)"],
    assignedClass: "SSS 2B (Assistant Form Tutor)",
    officeLocation: "ICT Lab, Tech Wing",
    createdAt: new Date(),
    updatedAt: new Date(),
  };
  memoryStore.teachers.set(demoTeacher4.id, demoTeacher4);

  const demoTeacher5 = {
    id: "stf_005",
    tenantId: demoTenantId,
    campusId: demoCampusId,
    employeeNumber: "EMP-2024-007",
    employeeId: "EMP-2024-007",
    firstName: "Mary",
    lastName: "Okonkwo",
    fullName: "Nurse Mary (RN)",
    email: "clinic@greenfieldhigh.edu.ng",
    phone: "+234 812 999 0011",
    department: "Healthcare",
    role: "School Health Matron",
    qualification: "RN / RM Registered Nurse",
    specialization: "Pediatric & Emergency First Aid",
    status: "Active",
    isActive: true,
    dateJoined: "2024-02-01",
    campus: "Main Campus",
    subjectsTaught: [],
    assignedClass: "N/A (Clinic)",
    officeLocation: "School Health Bay, Room 1",
    createdAt: new Date(),
    updatedAt: new Date(),
  };
  memoryStore.teachers.set(demoTeacher5.id, demoTeacher5);

  // Seed Staff Salary Profiles & Payroll Register
  const staffSalaryData = [
    {
      staffUserId: "stf_001",
      staff: "Dr. Kenneth Eze",
      staffId: "STF-2025-001",
      role: "Vice Principal (Academics)",
      department: "Administration",
      basicSalary: 280000,
      housingAllowance: 25000,
      transportAllowance: 15000,
      otherAllowances: 5000,
      bankName: "Zenith Bank Plc",
      accountNumber: "1029384756",
      allowanceBreakdown: [
        { name: "Housing Allowance", amount: 25000 },
        { name: "Transport Subsidy", amount: 15000 },
        { name: "Admin Duty Stipend", amount: 5000 },
      ],
    },
    {
      staffUserId: "stf_002",
      staff: "Mrs. Folashade Adebayo",
      staffId: "STF-2025-002",
      role: "Senior Science Teacher",
      department: "Sciences",
      basicSalary: 210000,
      housingAllowance: 18000,
      transportAllowance: 0,
      otherAllowances: 12000,
      bankName: "Guaranty Trust Bank",
      accountNumber: "0192837465",
      allowanceBreakdown: [
        { name: "Housing Allowance", amount: 18000 },
        { name: "Science Lab Duty Allowance", amount: 12000 },
      ],
    },
    {
      staffUserId: "stf_003",
      staff: "Mr. Obinna Okafor",
      staffId: "STF-2025-003",
      role: "Class Teacher (JSS 1)",
      department: "Arts & Humanities",
      basicSalary: 180000,
      housingAllowance: 15000,
      transportAllowance: 10000,
      otherAllowances: 0,
      bankName: "First Bank of Nigeria",
      accountNumber: "3049586712",
      allowanceBreakdown: [
        { name: "Housing Allowance", amount: 15000 },
        { name: "Transport Subsidy", amount: 10000 },
      ],
    },
    {
      staffUserId: "stf_004",
      staff: "Mr. Tunde Lawal",
      staffId: "STF-2025-004",
      role: "ICT Coordinator",
      department: "Technology",
      basicSalary: 195000,
      housingAllowance: 18000,
      transportAllowance: 0,
      otherAllowances: 17000,
      bankName: "Access Bank",
      accountNumber: "0029384751",
      allowanceBreakdown: [
        { name: "Housing Allowance", amount: 18000 },
        { name: "ICT Infrastructure Allowance", amount: 17000 },
      ],
    },
    {
      staffUserId: "stf_005",
      staff: "Nurse Mary (RN)",
      staffId: "STF-2025-005",
      role: "School Health Matron",
      department: "Healthcare",
      basicSalary: 175000,
      housingAllowance: 0,
      transportAllowance: 8000,
      otherAllowances: 12000,
      bankName: "Stanbic IBTC",
      accountNumber: "0019283749",
      allowanceBreakdown: [
        { name: "Clinical Hazard Allowance", amount: 12000 },
        { name: "Transport Subsidy", amount: 8000 },
      ],
    },
  ];

  staffSalaryData.forEach((s) => {
    // 1. Staff Salary Profile
    const profileKey = `${demoTenantId}_${s.staffUserId}`;
    memoryStore.staffSalaryProfiles.set(profileKey, {
      id: `ssp_${s.staffUserId}`,
      tenantId: demoTenantId,
      campusId: demoCampusId,
      staffUserId: s.staffUserId,
      basicSalary: s.basicSalary,
      housingAllowance: s.housingAllowance,
      transportAllowance: s.transportAllowance,
      otherAllowances: s.otherAllowances,
      customDeductions: 0,
      isPensionExempt: false,
      isNhfExempt: false,
      isNhisExempt: true,
      isTaxExempt: false,
      bankName: s.bankName,
      accountNumber: s.accountNumber,
      accountName: s.staff,
      isActive: true,
      createdAt: new Date('2025-08-01'),
      updatedAt: new Date('2025-08-01'),
    });

    // Calculate statutory figures using engine
    const calc = NigerianTaxCalculator.calculate({
      basicSalary: s.basicSalary,
      housingAllowance: s.housingAllowance,
      transportAllowance: s.transportAllowance,
      otherAllowances: s.otherAllowances,
    });

    // 2. September 2025 Payroll Record (Processed / Paid)
    const sepPayId = `pay_sep2025_${s.staffUserId}`;
    memoryStore.payroll.set(sepPayId, {
      id: sepPayId,
      tenantId: demoTenantId,
      campusId: demoCampusId,
      staffUserId: s.staffUserId,
      month: 9,
      year: 2025,
      basicSalary: calc.basicSalary,
      housingAllowance: calc.housingAllowance,
      transportAllowance: calc.transportAllowance,
      otherAllowances: calc.otherAllowances,
      grossSalary: calc.grossSalary,
      pensionEmployee: calc.pensionEmployee,
      pensionEmployer: calc.pensionEmployer,
      nhf: calc.nhf,
      nhis: calc.nhis,
      payeTax: calc.payeTax,
      otherDeductions: 0,
      totalDeductions: calc.totalDeductions,
      netSalary: calc.netSalary,
      currency: "NGN",
      status: "PAID",
      paymentDate: new Date("2025-09-28"),
      paymentReference: `PAY-REF-202509-${s.staffId}`,
      notes: "September 2025 Staff Remittance",
      breakdown: calc,
      createdAt: new Date("2025-09-25"),
    });

    // 3. October 2025 Payroll Record (Processed / Paid)
    const octPayId = `pay_oct2025_${s.staffUserId}`;
    memoryStore.payroll.set(octPayId, {
      id: octPayId,
      tenantId: demoTenantId,
      campusId: demoCampusId,
      staffUserId: s.staffUserId,
      month: 10,
      year: 2025,
      basicSalary: calc.basicSalary,
      housingAllowance: calc.housingAllowance,
      transportAllowance: calc.transportAllowance,
      otherAllowances: calc.otherAllowances,
      grossSalary: calc.grossSalary,
      pensionEmployee: calc.pensionEmployee,
      pensionEmployer: calc.pensionEmployer,
      nhf: calc.nhf,
      nhis: calc.nhis,
      payeTax: calc.payeTax,
      otherDeductions: 0,
      totalDeductions: calc.totalDeductions,
      netSalary: calc.netSalary,
      currency: "NGN",
      status: "PAID",
      paymentDate: new Date("2025-10-28"),
      paymentReference: `PAY-REF-202510-${s.staffId}`,
      notes: "October 2025 Staff Remittance",
      breakdown: calc,
      createdAt: new Date("2025-10-25"),
    });
  });

  // Seed Realistic Expenses
  const demoExpenses = [
    {
      id: "exp_001",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      category: "ACADEMIC",
      title: "Science Laboratory Equipment & Reagents",
      description: "Apparatus, chemicals, and glassware for SSS 1-3 Chemistry and Physics practicals.",
      amount: 350000,
      currency: "NGN",
      expenseDate: new Date("2025-09-12"),
      receiptUrl: "https://assets.schoolportal.ng/receipts/exp_001.pdf",
      approvedByUserId: demoOwnerId,
      createdAt: new Date("2025-09-12"),
    },
    {
      id: "exp_002",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      category: "FACILITIES",
      title: "Diesel Generator Fueling & Power Backup",
      description: "1,000 Liters diesel delivery for Main Campus central backup power generators.",
      amount: 280000,
      currency: "NGN",
      expenseDate: new Date("2025-09-18"),
      receiptUrl: "https://assets.schoolportal.ng/receipts/exp_002.pdf",
      approvedByUserId: demoOwnerId,
      createdAt: new Date("2025-09-18"),
    },
    {
      id: "exp_003",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      category: "TECHNOLOGY",
      title: "Campus Dedicated Fiber Optic Internet Subscription",
      description: "Monthly enterprise bandwidth (100 Mbps dedicated) for computer lab and administrative block.",
      amount: 120000,
      currency: "NGN",
      expenseDate: new Date("2025-10-01"),
      receiptUrl: "https://assets.schoolportal.ng/receipts/exp_003.pdf",
      approvedByUserId: demoOwnerId,
      createdAt: new Date("2025-10-01"),
    },
    {
      id: "exp_004",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      category: "STUDENT_SERVICES",
      title: "Inter-House Sports Meet & Athletic Equipment",
      description: "Medals, sportswear, first aid supplies, and refreshments for annual inter-house athletics.",
      amount: 95000,
      currency: "NGN",
      expenseDate: new Date("2025-10-08"),
      receiptUrl: "https://assets.schoolportal.ng/receipts/exp_004.pdf",
      approvedByUserId: demoOwnerId,
      createdAt: new Date("2025-10-08"),
    },
    {
      id: "exp_005",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      category: "ADMINISTRATION",
      title: "Examination Booklets & Office Stationery Supply",
      description: "Printed continuous assessment booklets, report sheets, printing paper, and toner cartridges.",
      amount: 150000,
      currency: "NGN",
      expenseDate: new Date("2025-10-14"),
      receiptUrl: "https://assets.schoolportal.ng/receipts/exp_005.pdf",
      approvedByUserId: demoOwnerId,
      createdAt: new Date("2025-10-14"),
    },
  ];

  demoExpenses.forEach((exp) => {
    memoryStore.expenses.set(exp.id, exp);
  });

  // ==========================================
  // SEED OPERATIONS: HOSTEL, TRANSPORT, CLINIC, LIBRARY, INVENTORY
  // ==========================================

  // 1. Hostels
  const demoHostels = [
    {
      id: "HST-01",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      name: "Nelson Mandela Hall (Boys)",
      hall: "Nelson Mandela Hall (Boys)",
      code: "HST-01",
      gender: "Boys",
      wardenName: "Mr. Chukwuma Okafor",
      warden: "Mr. Chukwuma Okafor",
      wardenPhone: "+234 803 999 1122",
      rooms: 40,
      totalRooms: 40,
      totalBeds: 160,
      occupiedBeds: 148,
      status: "Occupied",
      residents: [
        { student: "Chinedu Okafor", class: "JSS 1A", roomNumber: "Room 102", bedSpace: "Bed B (Upper)", dateJoined: "2025-09-01" },
        { student: "Adetunji Adebayo", class: "SSS 2A", roomNumber: "Room 204", bedSpace: "Bed A (Lower)", dateJoined: "2025-09-01" },
        { student: "Emeka Nwosu", class: "SSS 3A", roomNumber: "Room 301", bedSpace: "Bed A (Lower)", dateJoined: "2025-08-30" },
      ],
      createdAt: new Date("2025-08-15"),
      updatedAt: new Date("2025-09-01"),
    },
    {
      id: "HST-02",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      name: "Queen Amina Hall (Girls)",
      hall: "Queen Amina Hall (Girls)",
      code: "HST-02",
      gender: "Girls",
      wardenName: "Mrs. Zainab Danjuma",
      warden: "Mrs. Zainab Danjuma",
      wardenPhone: "+234 802 777 3344",
      rooms: 45,
      totalRooms: 45,
      totalBeds: 180,
      occupiedBeds: 170,
      status: "Occupied",
      residents: [
        { student: "Amina Yusuf", class: "JSS 2B", roomNumber: "Room G-105", bedSpace: "Bed B (Upper)", dateJoined: "2025-09-02" },
        { student: "Ngozi Eze", class: "SSS 1B", roomNumber: "Room G-208", bedSpace: "Bed A (Lower)", dateJoined: "2025-09-01" },
      ],
      createdAt: new Date("2025-08-15"),
      updatedAt: new Date("2025-09-01"),
    },
    {
      id: "HST-03",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      name: "Junior Boarding Block",
      hall: "Junior Boarding Block",
      code: "HST-03",
      gender: "Mixed (Junior Wings)",
      wardenName: "Mr. Segun Olatunji",
      warden: "Mr. Segun Olatunji",
      wardenPhone: "+234 805 444 8899",
      rooms: 20,
      totalRooms: 20,
      totalBeds: 80,
      occupiedBeds: 72,
      status: "Occupied",
      residents: [
        { student: "Samuel Balogun", class: "JSS 1B", roomNumber: "Room J-03", bedSpace: "Bed C (Lower)", dateJoined: "2025-09-03" },
      ],
      createdAt: new Date("2025-08-15"),
      updatedAt: new Date("2025-09-01"),
    },
  ];
  demoHostels.forEach((h) => memoryStore.hostels.set(h.id, h));

  // 2. Transport Routes
  const demoRoutes = [
    {
      id: "RT-01",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      name: "Route 1: Lekki - Ajah Express",
      routeName: "Route 1: Lekki - Ajah Express",
      vehicle: "Toyota Coaster (Bus 01)",
      plateNumber: "KJA-892-XA",
      driver: "Mr. Samuel Adeleke",
      driverName: "Mr. Samuel Adeleke",
      driverPhone: "+234 803 219 4810",
      capacity: 35,
      maxCapacity: 35,
      enrolled: 32,
      feePerTerm: 45000,
      fareAmount: 45000,
      status: "Active",
      stops: ["Ajah Roundabout (6:40 AM)", "Chevron Gate (6:55 AM)", "Jakande (7:10 AM)", "Campus Arrival (7:30 AM)"],
      passengers: [
        { student: "Chinedu Okafor", class: "JSS 1A", pickupStop: "Chevron Gate", contactPhone: "+234 802 111 2233" },
        { student: "Amina Yusuf", class: "JSS 2B", pickupStop: "Ajah Roundabout", contactPhone: "+234 803 444 5566" },
        { student: "Tobi Alabi", class: "SSS 1A", pickupStop: "Jakande", contactPhone: "+234 809 777 8899" },
      ],
      createdAt: new Date("2025-08-20"),
      updatedAt: new Date("2025-09-01"),
    },
    {
      id: "RT-02",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      name: "Route 2: Ikeja - Maryland Corridor",
      routeName: "Route 2: Ikeja - Maryland Corridor",
      vehicle: "Toyota HiAce (Bus 02)",
      plateNumber: "APP-401-BC",
      driver: "Mr. Sunday Bala",
      driverName: "Mr. Sunday Bala",
      driverPhone: "+234 802 984 1120",
      capacity: 18,
      maxCapacity: 18,
      enrolled: 16,
      feePerTerm: 40000,
      fareAmount: 40000,
      status: "Active",
      stops: ["Ikeja Underbridge (6:45 AM)", "Maryland Mall (7:05 AM)", "Anthony Village (7:15 AM)", "Campus Arrival (7:35 AM)"],
      passengers: [
        { student: "Adetunji Adebayo", class: "SSS 2A", pickupStop: "Maryland Mall", contactPhone: "+234 805 123 4567" },
      ],
      createdAt: new Date("2025-08-20"),
      updatedAt: new Date("2025-09-01"),
    },
    {
      id: "RT-03",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      name: "Route 3: Surulere - Yaba Axis",
      routeName: "Route 3: Surulere - Yaba Axis",
      vehicle: "Toyota Coaster (Bus 03)",
      plateNumber: "EKY-712-ZZ",
      driver: "Mr. Ibrahim Musa",
      driverName: "Mr. Ibrahim Musa",
      driverPhone: "+234 806 555 1928",
      capacity: 35,
      maxCapacity: 35,
      enrolled: 30,
      feePerTerm: 42000,
      fareAmount: 42000,
      status: "Active",
      stops: ["National Stadium (6:50 AM)", "Ojuelegba (7:05 AM)", "Yaba Tech Gate (7:20 AM)", "Campus Arrival (7:40 AM)"],
      passengers: [
        { student: "Emeka Nwosu", class: "SSS 3A", pickupStop: "National Stadium", contactPhone: "+234 808 999 0000" },
        { student: "Ngozi Eze", class: "SSS 1B", pickupStop: "Yaba Tech Gate", contactPhone: "+234 807 666 5555" },
      ],
      createdAt: new Date("2025-08-20"),
      updatedAt: new Date("2025-09-01"),
    },
  ];
  demoRoutes.forEach((r) => memoryStore.transportRoutes.set(r.id, r));

  // 3. Clinic Visits (Health)
  const demoClinicVisits = [
    {
      id: "CLN-2025-001",
      tenantId: demoTenantId,
      patientType: "STUDENT",
      patientId: "std_001",
      patientName: "Chinedu Okafor",
      student: "Chinedu Okafor",
      studentId: "STD-2025-001",
      admissionNumber: "STD-2025-001",
      class: "JSS 1A",
      complaint: "Mild fever & headache",
      chiefComplaint: "Mild fever & headache",
      temperature: "38.2°C",
      vitals: { temperature: 38.2, pulseRate: 84 },
      bloodGroup: "O+",
      allergies: "None Reported",
      diagnosis: "Malaria RDT negative, stress & dehydration. Paracetamol 500mg administered.",
      date: "2025-09-07",
      officer: "Nurse Mary (RN)",
      attendedByStaffName: "Nurse Mary (RN)",
      status: "Discharged",
      outcome: "DISCHARGED_TO_CLASS",
      parentNotified: true,
      admittedAt: new Date("2025-09-07T09:30:00Z"),
      dischargedAt: new Date("2025-09-07T11:00:00Z"),
      createdAt: new Date("2025-09-07T09:30:00Z"),
    },
    {
      id: "CLN-2025-002",
      tenantId: demoTenantId,
      patientType: "STUDENT",
      patientId: "std_002",
      patientName: "Amina Yusuf",
      student: "Amina Yusuf",
      studentId: "STD-2025-002",
      admissionNumber: "STD-2025-002",
      class: "JSS 2B",
      complaint: "Sprained left ankle during PE track session",
      chiefComplaint: "Sprained left ankle during PE track session",
      temperature: "36.8°C",
      vitals: { temperature: 36.8, pulseRate: 78 },
      bloodGroup: "B+",
      allergies: "Penicillin",
      diagnosis: "Cold compression applied with crepe bandage. Oral Ibuprofen given. Advised 48hr rest.",
      date: "2025-09-08",
      officer: "Nurse Mary (RN)",
      attendedByStaffName: "Nurse Mary (RN)",
      status: "Under Observation",
      outcome: "ADMITTED_TO_SICKBAY",
      parentNotified: true,
      admittedAt: new Date("2025-09-08T11:15:00Z"),
      dischargedAt: null,
      createdAt: new Date("2025-09-08T11:15:00Z"),
    },
    {
      id: "CLN-2025-003",
      tenantId: demoTenantId,
      patientType: "STUDENT",
      patientId: "std_003",
      patientName: "Adetunji Adebayo",
      student: "Adetunji Adebayo",
      studentId: "STD-2025-003",
      admissionNumber: "STD-2025-003",
      class: "SSS 2A",
      complaint: "Abdominal cramps after lunch break",
      chiefComplaint: "Abdominal cramps after lunch break",
      temperature: "37.1°C",
      vitals: { temperature: 37.1, pulseRate: 80 },
      bloodGroup: "A+",
      allergies: "Seafood",
      diagnosis: "Mild gastritis. Antacid suspension prescribed. Resting in recovery ward.",
      date: "2025-09-09",
      officer: "Dr. O. Adeleke (Visiting Medical Officer)",
      attendedByStaffName: "Dr. O. Adeleke (Visiting Medical Officer)",
      status: "Under Observation",
      outcome: "ADMITTED_TO_SICKBAY",
      parentNotified: false,
      admittedAt: new Date("2025-09-09T13:45:00Z"),
      dischargedAt: null,
      createdAt: new Date("2025-09-09T13:45:00Z"),
    },
    {
      id: "CLN-2025-004",
      tenantId: demoTenantId,
      patientType: "STUDENT",
      patientId: "std_004",
      patientName: "Ngozi Eze",
      student: "Ngozi Eze",
      studentId: "STD-2025-004",
      admissionNumber: "STD-2025-004",
      class: "SSS 1B",
      complaint: "Asthma tightness post-interhouse practice",
      chiefComplaint: "Asthma tightness post-interhouse practice",
      temperature: "36.9°C",
      vitals: { temperature: 36.9, pulseRate: 88 },
      bloodGroup: "AA / O+",
      allergies: "Dust & Pollen",
      diagnosis: "Salbutamol inhaler administered (2 puffs). Oxygen saturation 98%. Recovered well.",
      date: "2025-09-09",
      officer: "Nurse Mary (RN)",
      attendedByStaffName: "Nurse Mary (RN)",
      status: "Discharged",
      outcome: "DISCHARGED_TO_CLASS",
      parentNotified: true,
      admittedAt: new Date("2025-09-09T15:20:00Z"),
      dischargedAt: new Date("2025-09-09T16:30:00Z"),
      createdAt: new Date("2025-09-09T15:20:00Z"),
    },
  ];
  demoClinicVisits.forEach((v) => memoryStore.clinicVisits.set(v.id, v));

  // 4. Books (Library)
  const demoBooks = [
    {
      id: "BK-001",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      isbn: "978-0199147106",
      title: "New General Mathematics for JSS 1",
      author: "M.F. Macrae et al.",
      category: "Mathematics",
      shelf: "Aisle 3 - Bay B",
      shelfLocation: "Aisle 3 - Bay B",
      copies: 120,
      totalCopies: 120,
      available: 94,
      availableCopies: 94,
      status: "In Stock",
      loans: [
        { student: "Chinedu Okafor", class: "JSS 1A", issueDate: "2025-09-02", dueDate: "2025-09-16", status: "Active" },
        { student: "Amina Yusuf", class: "JSS 2B", issueDate: "2025-08-28", dueDate: "2025-09-11", status: "Active" },
      ],
      createdAt: new Date("2025-08-10"),
      updatedAt: new Date("2025-09-01"),
    },
    {
      id: "BK-002",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      isbn: "978-9781750242",
      title: "Countdown to WASSCE English",
      author: "Ogunsanwo et al.",
      category: "Languages",
      shelf: "Aisle 1 - Bay A",
      shelfLocation: "Aisle 1 - Bay A",
      copies: 80,
      totalCopies: 80,
      available: 65,
      availableCopies: 65,
      status: "In Stock",
      loans: [
        { student: "Adetunji Adebayo", class: "SSS 2A", issueDate: "2025-09-05", dueDate: "2025-09-19", status: "Active" },
      ],
      createdAt: new Date("2025-08-10"),
      updatedAt: new Date("2025-09-01"),
    },
    {
      id: "BK-003",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      isbn: "978-0582559196",
      title: "Senior Secondary Physics",
      author: "P.N. Okeke",
      category: "Sciences",
      shelf: "Aisle 4 - Bay C",
      shelfLocation: "Aisle 4 - Bay C",
      copies: 90,
      totalCopies: 90,
      available: 72,
      availableCopies: 72,
      status: "In Stock",
      loans: [
        { student: "Emeka Nwosu", class: "SSS 3A", issueDate: "2025-09-01", dueDate: "2025-09-15", status: "Active" },
      ],
      createdAt: new Date("2025-08-10"),
      updatedAt: new Date("2025-09-01"),
    },
    {
      id: "BK-004",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      isbn: "978-9780302484",
      title: "Modern Biology for Senior Secondary",
      author: "S.T. Ramalingam",
      category: "Sciences",
      shelf: "Aisle 4 - Bay D",
      shelfLocation: "Aisle 4 - Bay D",
      copies: 110,
      totalCopies: 110,
      available: 88,
      availableCopies: 88,
      status: "In Stock",
      loans: [],
      createdAt: new Date("2025-08-10"),
      updatedAt: new Date("2025-09-01"),
    },
    {
      id: "BK-005",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      isbn: "978-0195758368",
      title: "Things Fall Apart (Classic Edition)",
      author: "Chinua Achebe",
      category: "Literature",
      shelf: "Aisle 2 - Bay A",
      shelfLocation: "Aisle 2 - Bay A",
      copies: 75,
      totalCopies: 75,
      available: 45,
      availableCopies: 45,
      status: "In Stock",
      loans: [
        { student: "Ngozi Eze", class: "SSS 1B", issueDate: "2025-09-04", dueDate: "2025-09-18", status: "Active" },
      ],
      createdAt: new Date("2025-08-10"),
      updatedAt: new Date("2025-09-01"),
    },
  ];
  demoBooks.forEach((b) => memoryStore.books.set(b.id, b));

  // 5. School Assets & Inventory
  const demoAssets = [
    {
      id: "AST-001",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      name: "Student Wooden Desks & Chairs",
      item: "Student Wooden Desks & Chairs",
      assetTag: "AST-001",
      category: "Classroom Furniture",
      qty: 450,
      quantity: 450,
      unitCost: 18000,
      purchaseCost: 18000,
      location: "Main Campus Block A",
      condition: "Good",
      status: "In Use",
      custodian: "Estate Department",
      lastAudited: "2025-08-20",
      createdAt: new Date("2025-08-01"),
      updatedAt: new Date("2025-08-20"),
    },
    {
      id: "AST-002",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      name: "Interactive Smartboards 75-inch",
      item: "Interactive Smartboards 75-inch",
      assetTag: "AST-002",
      category: "ICT Equipment",
      qty: 24,
      quantity: 24,
      unitCost: 650000,
      purchaseCost: 650000,
      location: "Science Labs & ICT Suite",
      condition: "Excellent",
      status: "Operational",
      custodian: "Mr. Kunle Adeyemi (ICT Head)",
      lastAudited: "2025-09-01",
      createdAt: new Date("2025-08-15"),
      updatedAt: new Date("2025-09-01"),
    },
    {
      id: "AST-003",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      name: "Laboratory Compound Microscopes",
      item: "Laboratory Compound Microscopes",
      assetTag: "AST-003",
      category: "Science Lab",
      qty: 35,
      quantity: 35,
      unitCost: 85000,
      purchaseCost: 85000,
      location: "Biology Laboratory",
      condition: "Good",
      status: "Operational",
      custodian: "Dr. O. Adeleke",
      lastAudited: "2025-08-28",
      createdAt: new Date("2025-08-20"),
      updatedAt: new Date("2025-08-28"),
    },
    {
      id: "AST-004",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      name: "Magnetic Classroom Whiteboards",
      item: "Magnetic Classroom Whiteboards",
      assetTag: "AST-004",
      category: "Classroom Furniture",
      qty: 42,
      quantity: 42,
      unitCost: 25000,
      purchaseCost: 25000,
      location: "All Classrooms (Block A & B)",
      condition: "Good",
      status: "In Use",
      custodian: "Estate Department",
      lastAudited: "2025-08-15",
      createdAt: new Date("2025-08-10"),
      updatedAt: new Date("2025-08-15"),
    },
    {
      id: "AST-005",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      name: "Perkins 100kVA Soundproof Generator",
      item: "Perkins 100kVA Soundproof Generator",
      assetTag: "AST-005",
      category: "Facility & Utility",
      qty: 2,
      quantity: 2,
      unitCost: 14500000,
      purchaseCost: 14500000,
      location: "Power Station / Generator Bay",
      condition: "Maintenance Due",
      status: "Operational",
      custodian: "Engr. Patrick Igwe",
      lastAudited: "2025-09-05",
      createdAt: new Date("2025-07-15"),
      updatedAt: new Date("2025-09-05"),
    },
  ];
  demoAssets.forEach((a) => memoryStore.schoolAssets.set(a.id, a));

  // ==========================================
  // SEED COMMUNICATIONS, AUDIT LOGS, AND SUBSCRIPTIONS
  // ==========================================

  // 1. Communications / Broadcast Announcements
  const demoBroadcasts = [
    {
      id: "COM-2025-001",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      title: "End of First Half-Term Break Schedule",
      content: "Dear Parents, please be informed that mid-term recess begins Friday 12th September. Classes resume fully Monday 15th September. Ensure all holiday assignments are signed.",
      message: "Dear Parents, please be informed that mid-term recess begins Friday 12th September. Classes resume fully Monday 15th September. Ensure all holiday assignments are signed.",
      channel: "SMS & Email",
      channels: ["SMS", "EMAIL"],
      audience: "PARENTS",
      recipientGroup: "All Parents & Guardians",
      recipientCount: 1240,
      status: "Delivered",
      deliveryRate: "99.4%",
      sender: "Principal's Desk",
      sentAt: "2025-09-08 14:30",
      createdAt: new Date("2025-09-08T14:30:00Z"),
      updatedAt: new Date("2025-09-08T14:30:00Z"),
    },
    {
      id: "COM-2025-002",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      title: "Outstanding Term Tuition Reminder",
      content: "Reminder: Kindly complete outstanding tuition fees before the mid-term examinations commence. Use your student admission code on Paystack portal.",
      message: "Reminder: Kindly complete outstanding tuition fees before the mid-term examinations commence. Use your student admission code on Paystack portal.",
      channel: "SMS",
      channels: ["SMS"],
      audience: "PARENTS",
      recipientGroup: "Parents with Outstanding Balance",
      recipientCount: 312,
      status: "Delivered",
      deliveryRate: "98.1%",
      sender: "Bursary & Accounts",
      sentAt: "2025-09-06 09:15",
      createdAt: new Date("2025-09-06T09:15:00Z"),
      updatedAt: new Date("2025-09-06T09:15:00Z"),
    },
    {
      id: "COM-2025-003",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      title: "Inter-House Sports Heat Trials Timetable",
      content: "House captains are advised to submit track and field rosters by Wednesday noon. Athletic heats begin on the main campus field this Friday at 2:00 PM.",
      message: "House captains are advised to submit track and field rosters by Wednesday noon. Athletic heats begin on the main campus field this Friday at 2:00 PM.",
      channel: "Portal Noticeboard",
      channels: ["PORTAL"],
      audience: "ALL",
      recipientGroup: "All Staff & Students",
      recipientCount: 1650,
      status: "Published",
      deliveryRate: "100%",
      sender: "Sports Department",
      sentAt: "2025-09-04 11:00",
      createdAt: new Date("2025-09-04T11:00:00Z"),
      updatedAt: new Date("2025-09-04T11:00:00Z"),
    },
    {
      id: "COM-2025-004",
      tenantId: demoTenantId,
      campusId: demoCampusId,
      title: "PTA General Assembly & Executive Election",
      content: "You are cordially invited to the 2025/2026 PTA General Meeting in the School Auditorium. Agenda includes security review and STEM laboratory fundraising.",
      message: "You are cordially invited to the 2025/2026 PTA General Meeting in the School Auditorium. Agenda includes security review and STEM laboratory fundraising.",
      channel: "Email & Circular",
      channels: ["EMAIL"],
      audience: "ALL",
      recipientGroup: "All Parents & Staff",
      recipientCount: 1350,
      status: "Scheduled",
      deliveryRate: "Pending",
      sender: "PTA Secretary",
      sentAt: "2025-09-12 10:00",
      createdAt: new Date("2025-09-12T10:00:00Z"),
      updatedAt: new Date("2025-09-12T10:00:00Z"),
    },
  ];
  demoBroadcasts.forEach((b) => memoryStore.communications.set(b.id, b));

  // 2. Audit Logs
  const demoAuditLogs = [
    {
      id: "AUD-2025-0921",
      tenantId: demoTenantId,
      action: "FEE_PAYMENT_POSTED",
      actor: "Grace Danladi (Accountant)",
      actorRole: "ACCOUNTANT",
      resourceType: "INVOICE",
      resourceId: "INV-2025-001",
      resource: "Invoice #INV-2025-001 (Chinedu Okafor)",
      ipAddress: "197.210.84.12",
      userAgent: "Chrome 128 / macOS Sequoia",
      device: "Chrome 128 / macOS Sequoia",
      timestamp: "2025-09-09 14:28:10",
      status: "Success",
      metadata: {
        amount: "₦180,000",
        channel: "Paystack Direct",
        reference: "TRF-PSTK-9012384",
      },
      createdAt: new Date("2025-09-09T14:28:10Z"),
    },
    {
      id: "AUD-2025-0920",
      tenantId: demoTenantId,
      action: "GRADE_PUBLISHED",
      actor: "Dr. O. Adeleke (VP Academic)",
      actorRole: "SCHOOL_ADMIN",
      resourceType: "EXAM_PAPER",
      resourceId: "EXM-001",
      resource: "Continuous Assessment CA2 - JSS 1 Mathematics",
      ipAddress: "102.89.34.55",
      userAgent: "Firefox 130 / Windows 11",
      device: "Firefox 130 / Windows 11",
      timestamp: "2025-09-09 11:42:04",
      status: "Success",
      metadata: {
        class: "JSS 1A",
        studentsCount: 32,
        averageScore: "74.8%",
      },
      createdAt: new Date("2025-09-09T11:42:04Z"),
    },
    {
      id: "AUD-2025-0919",
      tenantId: demoTenantId,
      action: "STUDENT_ENROLLED",
      actor: "Mrs. Ngozi Eze (Registrar)",
      actorRole: "SCHOOL_ADMIN",
      resourceType: "STUDENT",
      resourceId: "STD-2025-045",
      resource: "Student Profile #STD-2025-045 (Fatima Bello)",
      ipAddress: "197.210.85.19",
      userAgent: "Safari 18.0 / iPadOS",
      device: "Safari 18.0 / iPadOS",
      timestamp: "2025-09-08 16:05:22",
      status: "Success",
      metadata: {
        classArm: "JSS 1B",
        guardian: "Alhaji Bello (08033221144)",
        tuitionBilled: "₦340,000",
      },
      createdAt: new Date("2025-09-08T16:05:22Z"),
    },
    {
      id: "AUD-2025-0918",
      tenantId: demoTenantId,
      action: "SECURITY_LOGIN_FAILED",
      actor: "unknown_user@school.edu",
      actorRole: "ANONYMOUS",
      resourceType: "AUTH_GATEWAY",
      resourceId: "/login",
      resource: "Authentication Gateway /login",
      ipAddress: "41.203.77.108",
      userAgent: "Python-requests / Linux",
      device: "Python-requests / Linux",
      timestamp: "2025-09-08 03:14:55",
      status: "Blocked",
      metadata: {
        reason: "MFA challenge timeout - IP rate-limited for 15 minutes",
        geo: "Lagos, Nigeria",
      },
      createdAt: new Date("2025-09-08T03:14:55Z"),
    },
    {
      id: "AUD-2025-0917",
      tenantId: demoTenantId,
      action: "STAFF_SALARY_DISBURSED",
      actor: "Grace Danladi (Accountant)",
      actorRole: "ACCOUNTANT",
      resourceType: "PAYROLL",
      resourceId: "PAY-2025-08",
      resource: "August 2025 Payroll Batch (48 Staff)",
      ipAddress: "197.210.84.12",
      userAgent: "Chrome 128 / macOS Sequoia",
      device: "Chrome 128 / macOS Sequoia",
      timestamp: "2025-09-01 09:00:00",
      status: "Success",
      metadata: {
        totalNetDisbursed: "₦14,250,000",
        bankBatchId: "NIBSS-ExtensiveSMS-8902",
      },
      createdAt: new Date("2025-09-01T09:00:00Z"),
    },
    {
      id: "AUD-2025-0916",
      tenantId: demoTenantId,
      action: "SECURITY_MFA_ENABLED",
      actor: "Mr. Tunde Lawal",
      actorRole: "TEACHER",
      resourceType: "USER_SECURITY",
      resourceId: "usr_003",
      resource: "User Security Credentials",
      ipAddress: "197.210.84.12",
      userAgent: "Chrome 128 / Windows 11",
      device: "Chrome 128 / Windows 11",
      timestamp: "2025-08-30 10:15:20",
      status: "Success",
      metadata: {
        method: "TOTP Authenticator",
      },
      createdAt: new Date("2025-08-30T10:15:20Z"),
    },
  ];
  demoAuditLogs.forEach((l) => memoryStore.auditLogs.set(l.id, l));

  // 3. Subscriptions & Billing Invoices
  const demoSubscription = {
    id: `sub_${demoTenantId}`,
    tenantId: demoTenantId,
    planId: "pro",
    tier: "pro",
    name: "Professional Campus",
    price: "₦350,000",
    period: "/ term",
    status: "ACTIVE",
    billingCycle: "TERM",
    trialEndsAt: null,
    currentPeriodStart: new Date("2025-01-15"),
    currentPeriodEnd: new Date("2025-12-31"),
    maxStudents: 1500,
    maxCampuses: 3,
    maxStaff: 100,
    storageLimitMb: 51200,
    messagingQuota: 5000,
    features: [
      "Up to 1,500 Students",
      "Up to 3 Campuses",
      "Custom School Domain (SSL)",
      "Paystack & Flutterwave Online Fees",
      "Full Operations Suite (Hostel, Transport, Clinic)",
      "Automated SMS & WhatsApp Alerts",
      "Priority 24/7 WhatsApp Support",
    ],
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date("2025-01-15"),
  };
  memoryStore.subscriptions.set(demoSubscription.id, demoSubscription);

  const demoSubInvoices = [
    {
      id: "SUB-INV-2025-01",
      tenantId: demoTenantId,
      date: "Jan 15, 2025",
      plan: "Professional Campus (First Term 2025)",
      amount: "₦350,000",
      method: "Paystack Direct Debit",
      status: "Paid",
      createdAt: new Date("2025-01-15"),
    },
    {
      id: "SUB-INV-2024-03",
      tenantId: demoTenantId,
      date: "Sep 10, 2024",
      plan: "Professional Campus (Third Term 2024)",
      amount: "₦350,000",
      method: "Bank Transfer (GTBank)",
      status: "Paid",
      createdAt: new Date("2024-09-10"),
    },
    {
      id: "SUB-INV-2024-02",
      tenantId: demoTenantId,
      date: "May 02, 2024",
      plan: "Professional Campus (Second Term 2024)",
      amount: "₦350,000",
      method: "Paystack Direct Debit",
      status: "Paid",
      createdAt: new Date("2024-05-02"),
    },
  ];
  demoSubInvoices.forEach((inv) => memoryStore.subscriptionInvoices.set(inv.id, inv));

  return memoryStore;
}
