export const API_PREFIX = 'api/v1';

export const ApiRoutes = {
  HEALTH: 'health',
  AUTH: `${API_PREFIX}/auth`,
  TENANCY: `${API_PREFIX}/tenant`,
  CAMPUSES: `${API_PREFIX}/campuses`,
  USERS: `${API_PREFIX}/users`,
  ROLES: `${API_PREFIX}/roles`,
  PERMISSIONS: `${API_PREFIX}/permissions`,
  ACADEMICS: `${API_PREFIX}/academics`,
  STUDENTS: `${API_PREFIX}/students`,
  PARENTS: `${API_PREFIX}/parents`,
  TEACHERS: `${API_PREFIX}/teachers`,
  ATTENDANCE: `${API_PREFIX}/attendance`,
  TIMETABLE: `${API_PREFIX}/timetable`,
  HOMEWORK: `${API_PREFIX}/homework`,
  EXAMINATIONS: `${API_PREFIX}/examinations`,
  RESULTS: `${API_PREFIX}/results`,
  FEES: `${API_PREFIX}/fees`,
  PAYMENTS: `${API_PREFIX}/payments`,
  PAYROLL: `${API_PREFIX}/payroll`,
  EXPENSES: `${API_PREFIX}/expenses`,
  TRANSPORT: `${API_PREFIX}/transport`,
  COMMUNICATIONS: `${API_PREFIX}/communications`,
  NOTIFICATIONS: `${API_PREFIX}/notifications`,
  FILES: `${API_PREFIX}/files`,
  REPORTS: `${API_PREFIX}/reports`,
  SUBSCRIPTION: `${API_PREFIX}/subscription`,
  BILLING: `${API_PREFIX}/billing`,
  AUDIT: `${API_PREFIX}/audit`,
} as const;
